const MGW={version:1,key:'moneygowhere-db-v1',state:{month:new Date(),range:1},cats:{Groceries:'🛒','Kids Essentials':'👶',Utilities:'💡',Household:'🏠',Transport:'🚗','Loans & Commitments':'💳',Taxes:'🧾',Lifestyle:'🍽️',Savings:'🐷',Investment:'📈',Other:'📦'}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function emptyDB(){return{version:MGW.version,expenses:[],income:[],budgets:{monthly:0,categories:{}},settings:{currency:'SGD'}}}
function load(){try{return Object.assign(emptyDB(),JSON.parse(localStorage.getItem(MGW.key)||'{}'))}catch{return emptyDB()}}
let db=load(); function save(){localStorage.setItem(MGW.key,JSON.stringify(db));renderAll()}
function money(v){return new Intl.NumberFormat('en-SG',{style:'currency',currency:db.settings.currency||'SGD'}).format(Number(v)||0)}
function ym(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function monthName(d){return d.toLocaleDateString('en-SG',{month:'long',year:'numeric'})}
function monthShift(d,n){return new Date(d.getFullYear(),d.getMonth()+n,1)}
function monthExpenses(d){let m=ym(d);return db.expenses.filter(x=>String(x.date||'').startsWith(m))}
function monthIncome(d){let m=ym(d);return db.income.filter(x=>String(x.date||'').startsWith(m))}
function sum(a,k='amount'){return a.reduce((t,x)=>t+(Number(x[k])||0),0)}
function totals(d){let ex=sum(monthExpenses(d)),inc=monthIncome(d),net=inc.reduce((t,x)=>t+(Number(x.netSalary)||0)+(Number(x.bonus)||0)+(Number(x.oneOff)||0),0);return{ex,net}}
function delta(cur,prev){if(!prev)return 'No prior comparison';let p=(cur-prev)/prev*100;return `${p>=0?'↑':'↓'} ${Math.abs(p).toFixed(0)}% vs previous month`}
function catTotals(list){let o={};list.forEach(x=>o[x.category]=(o[x.category]||0)+(Number(x.amount)||0));return Object.entries(o).sort((a,b)=>b[1]-a[1])}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function budgetClass(p){return p>=100?'over':p>=90?'almost':p>=80?'watch':''}
function renderDashboard(){let d=MGW.state.month,{ex,net}=totals(d),prev=totals(monthShift(d,-1)),budget=Number(db.budgets.monthly)||0,p=budget?ex/budget*100:0;$('#monthLabel').textContent=monthName(d);$('#netIncome').textContent=money(net);$('#spentTotal').textContent=money(ex);$('#remainingTotal').textContent=money(net-ex);$('#budgetUsed').textContent=budget?`${p.toFixed(0)}%`:'—';$('#incomeDelta').textContent=delta(net,prev.net);$('#spentDelta').textContent=delta(ex,prev.ex);$('#budgetState').textContent=!budget?'No budget set':p<80?'Healthy':p<90?'Watch':p<100?'Almost over budget':'Exceeded';let bar=$('#budgetBar').parentElement;bar.className='progress '+budgetClass(p);$('#budgetBar').style.width=`${Math.min(p,100)}%`;$('#budgetCopy').textContent=budget?`${money(ex)} of ${money(budget)} used`:'Set a monthly budget to start monitoring.';$('#budgetRemaining').textContent=budget?`${money(Math.max(budget-ex,0))} left`:'';let alert='Add a few expenses and MoneyGoWhere will start surfacing useful insights here.';if(budget){alert=p>=100?`Money went there 😅 You are ${money(ex-budget)} over this month's budget.`:p>=90?`Almost there — only ${money(budget-ex)} remains in this month's budget.`:p>=80?`Steady ah... ${p.toFixed(0)}% of your monthly budget is already used.`:`Looking healthy — ${money(budget-ex)} remains in your monthly budget.`}let cats=catTotals(monthExpenses(d));if(cats.length){let [name,val]=cats[0];alert+=` ${MGW.cats[name]||'📦'} ${name} is currently your highest spending category at ${money(val)}.`}$('#budgetAlertText').textContent=alert;$('#alertDot').classList.toggle('hidden',!(budget&&p>=80));renderCats($('#topCategories'),cats.slice(0,5));renderTrend($('#trendBars'),6,'expense')}
function renderCats(el,cats){if(!cats.length){el.className='category-list empty-state';el.textContent='No spending data yet.';return}el.className='category-list';let max=cats[0][1]||1;el.innerHTML=cats.map(([n,v])=>`<div class="category-row"><div class="category-main"><span class="cat-icon">${MGW.cats[n]||'📦'}</span><div><strong>${n}</strong><small>${((v/sum(cats.map(([_,x])=>({amount:x}))))*100).toFixed(0)}% of spending</small></div></div><strong>${money(v)}</strong><div class="mini-bar"><i style="width:${v/max*100}%"></i></div></div>`).join('')}
function rangeMonths(n){let arr=[];for(let i=n-1;i>=0;i--)arr.push(monthShift(MGW.state.month,-i));return arr}
function renderTrend(el,n,type){let months=rangeMonths(n),vals=months.map(d=>{if(type==='expense')return totals(d).ex;let inc=monthIncome(d);return inc.reduce((t,x)=>t+(Number(x.netSalary)||0),0)}),max=Math.max(...vals,1);el.innerHTML=months.map((d,i)=>`<div class="trend-col"><i style="height:${Math.max(4,vals[i]/max*115)}px"></i><small>${d.toLocaleDateString('en-SG',{month:'short'})}</small></div>`).join('')}
function renderRecent(){let a=[...db.expenses].sort((x,y)=>String(y.date+y.time).localeCompare(String(x.date+x.time))).slice(0,12),el=$('#recentTransactions');if(!a.length){el.className='transaction-list empty-state';el.textContent='Nothing recorded yet.';return}el.className='transaction-list';el.innerHTML=a.map(x=>`<div class="tx"><span class="cat-icon">${MGW.cats[x.category]||'📦'}</span><div><b>${x.vendor||x.category}</b><small>${x.date}${x.location?' · '+x.location:''}</small></div><span class="amount">${money(x.amount)}</span></div>`).join('')}
function renderInsights(){let n=MGW.state.range,months=rangeMonths(n),list=db.expenses.filter(x=>months.some(d=>String(x.date).startsWith(ym(d)))),cats=catTotals(list),total=sum(list);$('#insightSummary').innerHTML=total?`<strong>${money(total)}</strong><p>${n===1?'this month':`across the last ${n} months`}${cats[0]?` · Top: ${MGW.cats[cats[0][0]]||''} ${cats[0][0]}`:''}</p>`:'<p>No expenses in this period yet.</p>';renderCats($('#insightCategories'),cats);renderTrend($('#salaryTrend'),12,'salary');let byYear={};db.income.forEach(x=>{let y=String(x.date).slice(0,4),b=Number(x.bonus)||0;if(b)byYear[y]=(byYear[y]||0)+b});$('#bonusHistory').innerHTML=Object.entries(byYear).sort().map(([y,v])=>`<div class="bonus-row"><span>${y} Bonus</span><strong>${money(v)}</strong></div>`).join('')||'<p class="empty-state">No bonus history yet.</p>'}
function renderAll(){renderDashboard();renderRecent();renderInsights()}
function nav(name){$$('.view').forEach(x=>x.classList.remove('active'));$(`#view-${name}`).classList.add('active');$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));$('#pageTitle').textContent={dashboard:'Dashboard',add:'Add',insights:'Insights',settings:'Settings'}[name]}
function catsOptions(sel=''){return Object.keys(MGW.cats).map(c=>`<option ${c===sel?'selected':''}>${c}</option>`).join('')}
function openModal(type,data={}){let m=$('#modal'),body=$('#modalBody'),title='';if(type==='expense'||type==='receipt'){title=type==='receipt'?'Scan Receipt':'Add Expense';body.innerHTML=expenseForm(type,data)}if(type==='income'){title='Add Income';body.innerHTML=incomeForm()}if(type==='budget'){title='Budgets';body.innerHTML=budgetForm()}$('#modalTitle').textContent=title;m.showModal();bindModal(type)}
function expenseForm(type,d={}){let today=new Date().toISOString().slice(0,10);return `${type==='receipt'?`<div class="ocr-box"><label><b>Receipt photo</b><input id="receiptFile" type="file" accept="image/*" capture="environment"></label><img id="receiptPreview" class="receipt-preview hidden"><p id="ocrStatus" class="status">Choose or take a receipt photo. OCR runs locally in your browser.</p></div>`:''}<form id="expenseForm" class="form-grid"><div class="field"><label>Date</label><input name="date" type="date" required value="${d.date||today}"></div><div class="field"><label>Time</label><input name="time" type="time" value="${d.time||''}"></div><div class="field"><label>Vendor</label><input name="vendor" value="${d.vendor||''}" placeholder="NTUC FairPrice"></div><div class="field"><label>Location</label><input name="location" value="${d.location||''}" placeholder="Tampines Mall"></div><div class="field"><label>Amount</label><input name="amount" type="number" min="0" step="0.01" required value="${d.amount||''}"></div><div class="field"><label>Currency</label><select name="currency"><option>SGD</option><option>MYR</option><option>USD</option></select></div><div class="field full"><label>Spending Type</label><select name="category" required><option value="">Select category</option>${catsOptions()}</select></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div><div class="field full"><button class="primary-btn">Save Expense</button></div></form>`}
function incomeForm(){let today=new Date().toISOString().slice(0,10);return `<form id="incomeForm" class="form-grid"><div class="field full"><label>Pay Date</label><input name="date" type="date" value="${today}" required></div><div class="field"><label>Base Salary</label><input name="baseSalary" type="number" step="0.01"></div><div class="field"><label>Net Salary</label><input name="netSalary" type="number" step="0.01"></div><div class="field"><label>Bonus</label><input name="bonus" type="number" step="0.01"></div><div class="field"><label>One-Off Payment</label><input name="oneOff" type="number" step="0.01"></div><div class="field full"><button class="primary-btn">Save Income</button></div></form>`}
function budgetForm(){return `<form id="budgetForm"><div class="field"><label>Overall Monthly Budget</label><input name="monthly" type="number" step="0.01" min="0" value="${db.budgets.monthly||''}"></div><h3>Category Budgets</h3><div class="form-grid">${Object.keys(MGW.cats).map(c=>`<div class="field"><label>${MGW.cats[c]} ${c}</label><input name="cat:${c}" type="number" step="0.01" min="0" value="${db.budgets.categories[c]||''}"></div>`).join('')}</div><div class="form-actions"><button class="primary-btn">Save Budgets</button></div></form>`}
function bindModal(type){if(type==='receipt')$('#receiptFile').addEventListener('change',scanReceipt);let ef=$('#expenseForm');if(ef)ef.onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(ef));o.id=`EXP-${Date.now()}`;o.amount=Number(o.amount);o.source=type==='receipt'?'receipt_scan':'manual';db.expenses.push(o);save();$('#modal').close();toast('Expense saved')};let inf=$('#incomeForm');if(inf)inf.onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(inf));['baseSalary','netSalary','bonus','oneOff'].forEach(k=>o[k]=Number(o[k])||0);o.id=`INC-${Date.now()}`;db.income.push(o);save();$('#modal').close();toast('Income saved')};let bf=$('#budgetForm');if(bf)bf.onsubmit=e=>{e.preventDefault();let fd=new FormData(bf);db.budgets.monthly=Number(fd.get('monthly'))||0;Object.keys(MGW.cats).forEach(c=>db.budgets.categories[c]=Number(fd.get('cat:'+c))||0);save();$('#modal').close();toast('Budgets updated')}}
async function scanReceipt(e){let file=e.target.files[0];if(!file)return;let img=$('#receiptPreview');img.src=URL.createObjectURL(file);img.classList.remove('hidden');let st=$('#ocrStatus');if(!window.Tesseract){st.textContent='OCR library unavailable. You can still enter the receipt details manually.';return}try{st.textContent='Reading receipt… this can take a moment.';let {data:{text}}=await Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')st.textContent=`Reading receipt… ${Math.round((m.progress||0)*100)}%`}});let p=parseReceipt(text),f=$('#expenseForm');Object.entries(p).forEach(([k,v])=>{if(v&&f.elements[k])f.elements[k].value=v});st.textContent='Receipt read. Please review every field and choose the spending type before saving.'}catch(err){st.textContent='Could not read this receipt automatically. Please enter the details manually.'}}
function parseReceipt(text){let lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean),out={};out.vendor=lines.find(x=>/[A-Za-z]{3}/.test(x)&&x.length<50)||'';let date=text.match(/\b(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})\b/);if(date){let y=date[3].length===2?'20'+date[3]:date[3];out.date=`${y}-${date[2].padStart(2,'0')}-${date[1].padStart(2,'0')}`}let time=text.match(/\b([01]?\d|2[0-3]):([0-5]\d)\b/);if(time)out.time=`${time[1].padStart(2,'0')}:${time[2]}`;let totals=[...text.matchAll(/(?:TOTAL|AMOUNT|NETT|GRAND TOTAL)[^\d]{0,15}(\d+[.,]\d{2})/gi)].map(m=>Number(m[1].replace(',','.')));if(!totals.length)totals=[...text.matchAll(/\b(\d+[.,]\d{2})\b/g)].map(m=>Number(m[1].replace(',','.')));if(totals.length)out.amount=Math.max(...totals).toFixed(2);out.location=lines.find(x=>/(road|rd\b|street|st\b|avenue|ave\b|mall|plaza|centre|center|singapore|#\d{2})/i.test(x)&&x!==out.vendor)||'';return out}
function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`MoneyGoWhere-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup exported')}
function importData(file){let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.expenses)||!Array.isArray(x.income))throw 0;db=Object.assign(emptyDB(),x);save();toast('Backup restored')}catch{toast('Invalid MoneyGoWhere backup')}};r.readAsText(file)}
function integrity(){let problems=0,seen=new Set();db.expenses.forEach(x=>{let sig=[x.date,x.time,x.vendor,x.amount].join('|');if(!x.date||!Number.isFinite(Number(x.amount)))problems++;if(seen.has(sig))problems++;seen.add(sig)});toast(problems?`${problems} potential data issue(s) found`:'Data integrity check passed')}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$$('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));$('#closeModal').onclick=()=>$('#modal').close();$('#prevMonth').onclick=()=>{MGW.state.month=monthShift(MGW.state.month,-1);renderAll()};$('#nextMonth').onclick=()=>{MGW.state.month=monthShift(MGW.state.month,1);renderAll()};$$('#insightRange button').forEach(b=>b.onclick=()=>{$$('#insightRange button').forEach(x=>x.classList.remove('active'));b.classList.add('active');MGW.state.range=Number(b.dataset.range);renderInsights()});$('#exportBtn').onclick=exportData;$('#importInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('#integrityBtn').onclick=integrity;$('#resetBtn').onclick=()=>{if(confirm('Delete all MoneyGoWhere data on this device?')){db=emptyDB();save();toast('Local data reset')}};$('#alertBtn').onclick=()=>toast($('#budgetAlertText').textContent);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});renderAll();