const MGW={version:2,key:'moneygowhere-db-v1',state:{month:new Date(),range:1},cats:{Groceries:'🛒','Kids Essentials':'👶',Utilities:'💡',Household:'🏠',Transport:'🚗','Loans & Commitments':'💳',Installments:'🧾',Taxes:'🧾',Lifestyle:'🍽️','Food & Beverages':'🍴',Healthcare:'🏥',Subscription:'🔁',Insurance:'🛡️',Telecom:'📱',Savings:'🐷',Investment:'📈',Other:'📦'}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function emptyDB(){if(window.MGWDatabaseSchema?.empty)return window.MGWDatabaseSchema.empty();return{app:'MoneyGoWhere',version:MGW.version,schemaVersion:2,dataVersion:20,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),expenses:[],income:[],budgets:{monthly:0,categories:{}},settings:{currency:'SGD'},creditAccounts:[],creditPayments:[],payLaterAccounts:[],payLaterPayments:[],monthlyCommitments:[],recurringIncome:[],recurringCommitments:[],recurringBills:[],recurringItems:[],recurringModelMeta:{version:2,lastSyncedAt:null,itemCount:0},transactionModelMeta:{version:2,lastSyncedAt:null,expenseCount:0,incomeCount:0,duplicateFingerprintCount:0},walletAccounts:[],bankAccounts:[],accounts:[],paymentSourceMap:{},accountModelMeta:{version:2,lastSyncedAt:null,accountCount:0},importQueue:[],importHistory:[],receiptImportQueue:[],receiptImportHistory:[],importQuarantine:{expenses:[],income:[],history:[],receiptHistory:[]},backupMeta:{},schemaMeta:{migratedFrom:null,lastMigratedAt:null}}}
function load(){try{return Object.assign(emptyDB(),JSON.parse(localStorage.getItem(MGW.key)||'{}'))}catch{return emptyDB()}}
let db=load();
function adoptDatabase(next){if(!next||typeof next!=='object')return db;db=next;window.db=next;return db}
window.MGWAdoptDatabase=adoptDatabase;
function save(){if(window.MGWDatabaseSchema?.touch)db=window.MGWDatabaseSchema.touch(db);localStorage.setItem(MGW.key,JSON.stringify(db));window.db=db;renderAll()}
function money(v){return new Intl.NumberFormat('en-SG',{style:'currency',currency:db.settings.currency||'SGD'}).format(Number(v)||0)}
function ym(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function monthName(d){return d.toLocaleDateString('en-SG',{month:'long',year:'numeric'})}
function monthShift(d,n){return new Date(d.getFullYear(),d.getMonth()+n,1)}
function monthExpenses(d){let m=ym(d);return db.expenses.filter(x=>String(x.date||'').startsWith(m))}
function monthIncome(d){let m=ym(d);return db.income.filter(x=>String(x.date||'').startsWith(m))}
function sum(a,k='amount'){return a.reduce((t,x)=>t+(Number(x[k])||0),0)}
function totals(d){let ex=sum(monthExpenses(d)),inc=monthIncome(d),net=inc.reduce((t,x)=>t+(Number(x.netSalary)||0)+(Number(x.bonus)||0)+(Number(x.oneOff)||0),0);return{ex,net}}
function delta(cur,prev){if(!prev)return 'No prior comparison';let p=(cur-prev)/prev*100;return `${p>=0?'↑':'↓'} ${Math.abs(p).toFixed(0)}% vs previous month`}
function catTotals(list){let o={};list.forEach(x=>o[x.category]=(o[x.category]||0)+(Number(x.amount)||0));return Object.entries(o).sort((a,b)=>b[1]-a[1])}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function budgetClass(p){return p>=100?'over':p>=90?'almost':p>=80?'watch':''}
function renderDashboard(){let d=MGW.state.month,{ex,net}=totals(d),prev=totals(monthShift(d,-1)),budget=Number(db.budgets.monthly)||0,p=budget?ex/budget*100:0;$('#monthLabel').textContent=monthName(d);$('#netIncome').textContent=money(net);$('#spentTotal').textContent=money(ex);$('#remainingTotal').textContent=money(net-ex);$('#budgetUsed').textContent=budget?`${p.toFixed(0)}%`:'—';$('#incomeDelta').textContent=delta(net,prev.net);$('#spentDelta').textContent=delta(ex,prev.ex);$('#budgetState').textContent=!budget?'No budget set':p<80?'Healthy':p<90?'Watch':p<100?'Almost over budget':'Exceeded';let bar=$('#budgetBar').parentElement;bar.className='progress '+budgetClass(p);$('#budgetBar').style.width=`${Math.min(p,100)}%`;$('#budgetCopy').textContent=budget?`${money(ex)} of ${money(budget)} used`:'Set a monthly budget to start monitoring.';$('#budgetRemaining').textContent=budget?`${money(Math.max(budget-ex,0))} left`:'';let alert='Add a few expenses and MoneyGoWhere will start surfacing useful insights here.';if(budget){alert=p>=100?`Money went there 😅 You are ${money(ex-budget)} over this month's budget.`:p>=90?`Almost there — only ${money(budget-ex)} remains in this month's budget.`:p>=80?`Steady ah... ${p.toFixed(0)}% of your monthly budget is already used.`:`Looking healthy — ${money(budget-ex)} remains in your monthly budget.`}let cats=catTotals(monthExpenses(d));if(cats.length){let [name,val]=cats[0];alert+=` ${MGW.cats[name]||'📦'} ${name} is currently your highest spending category at ${money(val)}.`}$('#budgetAlertText').textContent=alert;$('#alertDot').classList.toggle('hidden',!(budget&&p>=80));renderCats($('#topCategories'),cats.slice(0,5));renderTrend($('#trendBars'),6,'expense')}
function renderCats(el,cats){if(!cats.length){el.className='category-list empty-state';el.textContent='No spending data yet.';return}el.className='category-list';const total=cats.reduce((t,[,x])=>t+(Number(x)||0),0)||1,max=cats[0][1]||1;el.innerHTML=cats.map(([n,v])=>`<div class="category-row"><div class="category-main"><span class="cat-icon">${MGW.cats[n]||'📦'}</span><div><strong>${esc(n)}</strong><small>${((v/total)*100).toFixed(0)}% of spending</small></div></div><strong>${money(v)}</strong><div class="mini-bar"><i style="width:${v/max*100}%"></i></div></div>`).join('')}
function rangeMonths(n){let arr=[];for(let i=n-1;i>=0;i--)arr.push(monthShift(MGW.state.month,-i));return arr}
function renderTrend(el,n,type){let months=rangeMonths(n),vals=months.map(d=>{if(type==='expense')return totals(d).ex;let inc=monthIncome(d);return inc.reduce((t,x)=>t+(Number(x.netSalary)||0),0)}),max=Math.max(...vals,1);el.innerHTML=months.map((d,i)=>`<div class="trend-col"><i style="height:${Math.max(4,vals[i]/max*115)}px"></i><small>${d.toLocaleDateString('en-SG',{month:'short'})}</small></div>`).join('')}
function renderRecent(){let a=[...db.expenses].sort((x,y)=>String((y.date||'')+(y.time||'')).localeCompare(String((x.date||'')+(x.time||'')))).slice(0,12),el=$('#recentTransactions');if(!a.length){el.className='transaction-list empty-state';el.textContent='Nothing recorded yet.';return}el.className='transaction-list';el.innerHTML=a.map(x=>`<div class="tx"><span class="cat-icon">${MGW.cats[x.category]||'📦'}</span><div><b>${esc(x.vendor||x.category||'Expense')}</b><small>${esc(`${x.date||''}${x.location?' · '+x.location:''}`)}</small></div><span class="amount">${money(x.amount)}</span></div>`).join('')}
function renderInsights(){let n=MGW.state.range,months=rangeMonths(n),list=db.expenses.filter(x=>months.some(d=>String(x.date).startsWith(ym(d)))),cats=catTotals(list),total=sum(list);$('#insightSummary').innerHTML=total?`<strong>${money(total)}</strong><p>${n===1?'this month':`across the last ${n} months`}${cats[0]?` · Top: ${MGW.cats[cats[0][0]]||''} ${esc(cats[0][0])}`:''}</p>`:'<p>No expenses in this period yet.</p>';renderCats($('#insightCategories'),cats);renderTrend($('#salaryTrend'),12,'salary');let byYear={};db.income.forEach(x=>{let y=String(x.date).slice(0,4),b=Number(x.bonus)||0;if(b)byYear[y]=(byYear[y]||0)+b});$('#bonusHistory').innerHTML=Object.entries(byYear).sort().map(([y,v])=>`<div class="bonus-row"><span>${esc(y)} Bonus</span><strong>${money(v)}</strong></div>`).join('')||'<p class="empty-state">No bonus history yet.</p>'}
function renderAll(){renderDashboard();renderRecent();if(document.querySelector('#view-insights')?.classList.contains('active'))renderInsights()}
window.renderAll=renderAll;
window.nav=nav;
document.addEventListener('mgw:data-restored',e=>requestAnimationFrame(()=>{adoptDatabase(e.detail?.database||window.db);renderAll();window.MGWSalaryTrends?.render?.();window.MGWHistoryCollapse?.refresh?.()}));
function nav(name){$$('.view').forEach(x=>x.classList.remove('active'));const view=$(`#view-${name}`);if(!view)return;view.classList.add('active');$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));$('#pageTitle').textContent={dashboard:'Dashboard',add:'Add',insights:'Insights',settings:'Settings'}[name]||'MoneyGoWhere';if(name==='insights')requestAnimationFrame(()=>{(window.MGWRenderInsights||renderInsights)();window.MGWSalaryTrends?.render?.(window.db||db)})}
function catsOptions(sel=''){return Object.keys(MGW.cats).map(c=>`<option ${c===sel?'selected':''}>${esc(c)}</option>`).join('')}
function openModal(type,data={}){let m=$('#modal'),body=$('#modalBody'),title='';if(type==='expense'||type==='receipt'){title=type==='receipt'?'Scan Receipt':'Add Expense';body.innerHTML=expenseForm(type,data)}if(type==='income'){title='Add Income';body.innerHTML=incomeForm()}if(type==='budget'){title='Budgets';body.innerHTML=budgetForm()}$('#modalTitle').textContent=title;m.showModal();bindModal(type)}
function expenseForm(type,d={}){let today=new Date().toISOString().slice(0,10);return `${type==='receipt'?`<div class="ocr-box"><label><b>Receipt image or PDF</b><input id="receiptFile" type="file" accept="image/*,application/pdf,.pdf"></label><img id="receiptPreview" class="receipt-preview hidden"><p id="ocrStatus" class="status">Choose a receipt image or PDF. Crop or rotate before reading, then review before saving.</p></div>`:''}<form id="expenseForm" class="form-grid"><div class="field"><label>Date</label><input name="date" type="date" required value="${esc(d.date||today)}"></div><div class="field"><label>Time</label><input name="time" type="time" value="${esc(d.time||'')}"></div><div class="field"><label>Vendor</label><input name="vendor" value="${esc(d.vendor||'')}" placeholder="Merchant name"></div><div class="field"><label>Location</label><input name="location" value="${esc(d.location||'')}" placeholder="Optional location"></div><div class="field"><label>Amount</label><input name="amount" type="number" min="0" step="0.01" required value="${esc(d.amount||'')}"></div><div class="field"><label>Currency</label><select name="currency"><option>SGD</option><option>MYR</option><option>USD</option></select></div><div class="field full"><label>Spending Type</label><select name="category" required><option value="">Select category</option>${catsOptions()}</select></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div>${type==='receipt'?window.MGWReceiptReview.fields():''}<div class="field full"><button class="primary-btn">Save Expense</button></div></form>`}
function incomeForm(){let today=new Date().toISOString().slice(0,10);return `<form id="incomeForm" class="form-grid"><div class="field full"><label>Pay Date</label><input name="date" type="date" value="${today}" required></div><div class="field"><label>Base Salary</label><input name="baseSalary" type="number" step="0.01"></div><div class="field"><label>Net Salary</label><input name="netSalary" type="number" step="0.01"></div><div class="field"><label>Bonus</label><input name="bonus" type="number" step="0.01"></div><div class="field"><label>One-Off Payment</label><input name="oneOff" type="number" step="0.01"></div><div class="field full"><label>Deposit to bank (optional)</label><select name="depositAccountId">${window.MGWWalletBalances.bankOptions()}</select><small>Linked net salary, bonus and one-off income add to the tracked bank balance.</small></div><div class="field full"><button class="primary-btn">Save Income</button></div></form>`}
function budgetForm(){return `<form id="budgetForm"><div class="field"><label>Overall Monthly Budget</label><input name="monthly" type="number" step="0.01" min="0" value="${db.budgets.monthly||''}"></div><h3>Category Budgets</h3><div class="form-grid">${Object.keys(MGW.cats).map(c=>`<div class="field"><label>${MGW.cats[c]} ${esc(c)}</label><input name="cat:${esc(c)}" type="number" step="0.01" min="0" value="${db.budgets.categories[c]||''}"></div>`).join('')}</div><div class="form-actions"><button class="primary-btn">Save Budgets</button></div></form>`}
function recurringExpenseMatch(o){
  const engine=window.MGWRecurringEngine;if(!engine||!o||!o.amount)return null;
  try{engine.sync(db,{persist:false})}catch{}
  const vendor=String(o.vendor||o.merchant||'').trim().toLowerCase(),amount=Number(o.amount)||0,day=Number(String(o.date||'').slice(8,10))||0;
  if(!vendor)return null;
  const rows=Array.isArray(db.recurringItems)?db.recurringItems:[];
  return rows.filter(x=>x&&x.active!==false&&x.type!=='income'&&x.type!=='installment').map(x=>{
    const name=String(x.merchant||x.name||'').trim().toLowerCase(),expected=Number(x.amount)||0,due=Number(x.day)||0;
    const merchant=name&&(vendor===name||vendor.includes(name)||name.includes(vendor));
    const amountOk=expected>0&&Math.abs(amount-expected)<=Math.max(1,expected*.08);
    const dayOk=!due||!day||Math.abs(day-due)<=5;
    return {x,score:(merchant?2:0)+(amountOk?2:0)+(dayOk?1:0)};
  }).filter(v=>v.score>=4).sort((a,b)=>b.score-a.score)[0]?.x||null;
}
function recommendRecurringAction(o){
  const match=recurringExpenseMatch(o);if(!match)return;
  const label=match.name||match.merchant||'recurring payment';
  setTimeout(()=>{if(confirm(`This looks like your recurring “${label}” payment. Link this transaction to the recurring schedule?`)){const saved=db.expenses.find(x=>x.id===o.id);if(!saved)return;saved.recurringItemId=match.id;saved.recurringMatch='confirmed';save();toast('Recurring payment linked')}else toast('Expense saved without recurring link')},0);
}
function bindModal(type){if(type==='receipt')$('#receiptFile').addEventListener('change',scanReceipt);let ef=$('#expenseForm');if(ef&&type==='receipt')ef.addEventListener('input',e=>{if(e.target.name!=='receiptReviewed'&&ef.elements.receiptReviewed)ef.elements.receiptReviewed.checked=false});if(ef)ef.onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(ef));if(type==='receipt'){try{if(ef.dataset.receiptBusy==='1')throw Error('Wait for the current receipt scan to finish.');const result=ef._mgwReceiptResult;o.rawText=result?.rawText||'';o.receiptPage=result?.pageNumber||0;o.receiptPageCount=result?.pageCount||1;o.fullPDF=Boolean(result?.fullPDF);o.receiptInputMethod=result?.inputMethod||'manual_review';window.MGWReceiptReview.save(o,{reviewed:Boolean(ef.elements.receiptReviewed?.checked)});$('#modal').close();try{renderAll()}catch(err){console.warn('Receipt saved; display refresh failed',err)}toast('Receipt saved')}catch(err){toast(err.message)}return}o.id=`EXP-${Date.now()}`;o.amount=Number(o.amount);o.source=type==='receipt'?'receipt_scan':'manual';o=window.MGWTransactionEngine?.prepareExpense?window.MGWTransactionEngine.prepareExpense(o,db.expenses.length):o;db.expenses.push(o);save();$('#modal').close();toast('Expense saved');if(o.source==='manual')recommendRecurringAction(o)};let inf=$('#incomeForm');if(inf)inf.onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(inf));['baseSalary','netSalary','bonus','oneOff'].forEach(k=>o[k]=Number(o[k])||0);o.id=`INC-${Date.now()}`;o.source='manual';o=window.MGWTransactionEngine?.prepareIncome?window.MGWTransactionEngine.prepareIncome(o,db.income.length):o;db.income.push(o);save();document.dispatchEvent(new CustomEvent('mgw:income-changed',{detail:{id:o.id}}));$('#modal').close();toast('Income saved')};let bf=$('#budgetForm');if(bf)bf.onsubmit=e=>{e.preventDefault();let fd=new FormData(bf);db.budgets.monthly=Number(fd.get('monthly'))||0;Object.keys(MGW.cats).forEach(c=>db.budgets.categories[c]=Number(fd.get('cat:'+c))||0);save();$('#modal').close();toast('Budgets updated')}}
async function scanReceipt(e){const file=e.target.files?.[0];if(!file)return;const f=document.querySelector('#expenseForm'),st=document.querySelector('#ocrStatus');if(f?.dataset.receiptBusy==='1'){if(st)st.textContent='Finish the current receipt scan first.';return}if(f)f.dataset.receiptBusy='1';try{if(st)st.textContent='Loading receipt tools…';await window.MGWLoadImportFeatures?.();if(!window.MGWReceiptWorkbench)throw Error('Receipt tools unavailable');if(f)delete f.dataset.receiptBusy;if(!e.target.isConnected||f!==document.querySelector('#expenseForm'))return;return await window.MGWReceiptWorkbench.scanIntoForm(e)}catch(err){if(st)st.textContent='Could not load receipt tools. You can enter details manually.';if(f)delete f.dataset.receiptBusy}}
function parseReceipt(text){let lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean),out={};out.vendor=lines.find(x=>/[A-Za-z]{3}/.test(x)&&x.length<50)||'';let date=text.match(/\b(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})\b/);if(date){let y=date[3].length===2?'20'+date[3]:date[3];out.date=`${y}-${date[2].padStart(2,'0')}-${date[1].padStart(2,'0')}`}let time=text.match(/\b([01]?\d|2[0-3]):([0-5]\d)\b/);if(time)out.time=`${time[1].padStart(2,'0')}:${time[2]}`;let totals=[...text.matchAll(/(?:TOTAL|AMOUNT|NETT|GRAND TOTAL)[^\d]{0,15}(\d+[.,]\d{2})/gi)].map(m=>Number(m[1].replace(',','.')));if(!totals.length)totals=[...text.matchAll(/\b(\d+[.,]\d{2})\b/g)].map(m=>Number(m[1].replace(',','.')));if(totals.length)out.amount=Math.max(...totals).toFixed(2);out.location=lines.find(x=>/(road|rd\b|street|st\b|avenue|ave\b|mall|plaza|centre|center|singapore|#\d{2})/i.test(x)&&x!==out.vendor)||'';return out}
function exportData(){if(window.MGWMasterDB?.exportMasterDB)return window.MGWMasterDB.exportMasterDB();let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`MoneyGoWhere-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup exported')}
function importData(file){if(window.MGWMasterDB?.restoreFile)return window.MGWMasterDB.restoreFile(file);let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.expenses)||!Array.isArray(x.income))throw 0;db=Object.assign(emptyDB(),x);window.db=db;save();toast('Backup restored')}catch{toast('Invalid MoneyGoWhere backup')}};r.readAsText(file)}
function integrity(){let problems=0,seen=new Set();db.expenses.forEach(x=>{let sig=[x.date,x.time,x.vendor,x.amount].join('|');if(!x.date||!Number.isFinite(Number(x.amount)))problems++;if(seen.has(sig))problems++;seen.add(sig)});toast(problems?`${problems} potential data issue(s) found`:'Data integrity check passed')}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$$('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));$('#closeModal').onclick=()=>$('#modal').close();$('#prevMonth').onclick=()=>{MGW.state.month=monthShift(MGW.state.month,-1);renderAll()};$('#nextMonth').onclick=()=>{MGW.state.month=monthShift(MGW.state.month,1);renderAll()};$$('#insightRange button').forEach(b=>b.onclick=()=>{$$('#insightRange button').forEach(x=>x.classList.remove('active'));b.classList.add('active');MGW.state.range=Number(b.dataset.range);renderInsights()});$('#exportBtn').onclick=exportData;$('#importInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('#integrityBtn').onclick=integrity;$('#resetBtn').onclick=()=>{if(confirm('Delete all MoneyGoWhere data on this device?')){db=emptyDB();window.db=db;save();toast('Local data reset')}};$('#alertBtn').onclick=()=>toast($('#budgetAlertText').textContent);renderAll();
