// MoneyGoWhere DEV — foreign-currency labels and SGD display helpers.
(()=>{'use strict';
const RELEASE='1.5.5-dev.35';let editing='';
const fx=()=>window.MGWCurrency;
const expense=id=>(db.expenses||[]).find(x=>String(x.id||'')===String(id||''));
const amountHtml=x=>fx()?.amountHtml(x)||money(Number(x?.amount)||0);
const amountText=x=>fx()?.amountText(x)||money(Number(x?.amount)||0);
const sgd=x=>fx()?.sgdAmount(x)??(Number(x?.amount)||0);
function enhanceSelects(){document.querySelectorAll('#expenseForm select[name="currency"],#mgwEditExpenseForm select[name="currency"]').forEach(sel=>{if(sel.dataset.mgwFxUi)return;const c=sel.value||'SGD';if(fx()?.currencyOptions){sel.innerHTML=fx().currencyOptions(c);sel.value=c}sel.dataset.mgwFxUi='1'})}
function decorate(){document.querySelectorAll('[data-expense-id]').forEach(row=>{const x=expense(row.dataset.expenseId);if(!x)return;const el=row.matches('.mgw-history-line')?row.querySelector(':scope > strong'):row.querySelector('.amount');if(el&&el.dataset.mgwFx!==amountText(x)){el.innerHTML=amountHtml(x);el.dataset.mgwFx=amountText(x)}});document.querySelectorAll('.mgw-history-merchant').forEach(g=>{const rows=[...g.querySelectorAll('.mgw-history-line[data-expense-id]')].map(r=>expense(r.dataset.expenseId)).filter(Boolean),el=g.querySelector(':scope > summary .mgw-history-right strong');if(el)el.textContent=money(rows.reduce((t,x)=>t+sgd(x),0))});document.querySelectorAll('.mgw-history-month').forEach(g=>{const rows=[...g.querySelectorAll('.mgw-history-line[data-expense-id]')].map(r=>expense(r.dataset.expenseId)).filter(Boolean),el=g.querySelector(':scope > summary .mgw-history-right strong');if(el)el.textContent=money(rows.reduce((t,x)=>t+sgd(x),0))});document.querySelectorAll('#mgwWalletImportQueue [data-id]').forEach(row=>{const x=(db.importQueue||[]).find(q=>String(q.id||'')===String(row.dataset.id||'')),el=row.querySelector(':scope > div:last-child > strong');if(x&&el&&el.dataset.mgwFx!==amountText(x)){el.innerHTML=amountHtml(x);el.dataset.mgwFx=amountText(x)}})}
function clearEditedFx(){const x=expense(editing);if(!x)return;delete x.sgdAmount;delete x.fxRateToSGD;delete x.fxRateDate;delete x.fxRateSource;localStorage.setItem(MGW.key,JSON.stringify(db));editing='';setTimeout(()=>fx()?.syncRates({force:true}),80)}
function boot(){document.addEventListener('click',e=>{const b=e.target.closest?.('[data-edit-expense]');if(b)editing=String(b.dataset.editExpense||'')},true);document.addEventListener('submit',e=>{if(e.target?.id==='mgwEditExpenseForm')setTimeout(clearEditedFx,0);if(e.target?.id==='expenseForm')setTimeout(()=>fx()?.syncRates({force:true}),80)},true);let queued=false;const apply=()=>{enhanceSelects();decorate()};apply();new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply()})}).observe(document.body,{subtree:true,childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.MGWCurrencyUI={version:RELEASE,refresh:decorate};
})();