// MoneyGoWhere v1.5.0 runtime compatibility layer.
// IMPORTANT: No personal finance records are bundled with the app.
const MGW_RUNTIME_RELEASE=Object.freeze({appVersion:'1.5.0',schemaVersion:1,dataVersion:6,cacheVersion:'1.5.0'});

function mgwCycleSettings(){const p=db?.settings?.payCycle||{};return{mode:p.mode==='payday'?'payday':'calendar',day:Math.min(31,Math.max(1,Number(p.day)||25))}}
function mgwSafeMonthDay(y,m,d){return new Date(y,m,Math.min(d,new Date(y,m+1,0).getDate()))}
function mgwDateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function mgwCycleBounds(anchor=MGW.state.month){const c=mgwCycleSettings(),y=anchor.getFullYear(),m=anchor.getMonth();return c.mode==='payday'?{start:mgwSafeMonthDay(y,m,c.day),end:mgwSafeMonthDay(y,m+1,c.day),mode:'payday'}:{start:new Date(y,m,1),end:new Date(y,m+1,1),mode:'calendar'}}
function mgwInCycle(x,anchor){const b=mgwCycleBounds(anchor),k=String(x?.date||'').slice(0,10);return Boolean(k)&&k>=mgwDateKey(b.start)&&k<mgwDateKey(b.end)}
function mgwCycleLabel(anchor=MGW.state.month){const b=mgwCycleBounds(anchor);if(b.mode==='calendar')return b.start.toLocaleDateString('en-SG',{month:'long',year:'numeric'});const e=new Date(b.end);e.setDate(e.getDate()-1);const same=b.start.getFullYear()===e.getFullYear();return `${b.start.toLocaleDateString('en-SG',{day:'numeric',month:'short',year:same?undefined:'numeric'})} – ${e.toLocaleDateString('en-SG',{day:'numeric',month:'short',year:'numeric'})}`}

if(typeof monthExpenses==='function')monthExpenses=d=>db.expenses.filter(x=>mgwInCycle(x,d));
if(typeof monthIncome==='function')monthIncome=d=>db.income.filter(x=>mgwInCycle(x,d));
if(typeof monthName==='function')monthName=d=>mgwCycleLabel(d);

if(typeof renderInsights==='function')renderInsights=function(){const n=MGW.state.range,months=rangeMonths(n),list=months.flatMap(d=>monthExpenses(d)),cats=catTotals(list),total=sum(list),isPay=mgwCycleSettings().mode==='payday';$('#insightSummary').innerHTML=total?`<strong>${money(total)}</strong><p>${n===1?(isPay?'this pay cycle':'this month'):`across the last ${n} ${isPay?'pay cycles':'months'}`}${cats[0]?` · Top: ${MGW.cats[cats[0][0]]||''} ${cats[0][0]}`:''}</p>`:'<p>No expenses in this period yet.</p>';renderCats($('#insightCategories'),cats);renderTrend($('#salaryTrend'),12,'salary');const byYear={};db.income.forEach(x=>{const y=String(x.date).slice(0,4),b=Number(x.bonus)||0;if(b)byYear[y]=(byYear[y]||0)+b});$('#bonusHistory').innerHTML=Object.entries(byYear).sort().map(([y,v])=>`<div class="bonus-row"><span>${y} Bonus</span><strong>${money(v)}</strong></div>`).join('')||'<p class="empty-state">No bonus history yet.</p>'};

function mgwCycleCard(){
  if(document.querySelector('#mgwPayCycleCard'))return;const settings=document.querySelector('#view-settings');if(!settings)return;const cfg=mgwCycleSettings(),card=document.createElement('article');card.className='card';card.id='mgwPayCycleCard';
  card.innerHTML=`<div class="card-head"><div><span class="section-icon">📅</span><b>Tracking Period</b></div></div><form id="mgwPayCycleForm" class="form-grid"><div class="field full"><label>Tabulation mode</label><select name="mode"><option value="calendar" ${cfg.mode==='calendar'?'selected':''}>Calendar month</option><option value="payday" ${cfg.mode==='payday'?'selected':''}>Pay cycle</option></select><small>Pay cycle groups income, expenses, budgets and insights from one payday to the day before the next.</small></div><div class="field full"><label>Payday / cycle start day</label><input name="day" type="number" min="1" max="31" value="${cfg.day}"><small>Example: day 25 means 25 Aug → 24 Sep. Short months use their last valid day.</small></div><div class="field full"><div class="status" id="mgwCyclePreview"></div></div><div class="field full"><button class="primary-btn">Save Tracking Period</button></div></form>`;
  settings.insertBefore(card,settings.querySelector('.privacy-note')||null);const f=card.querySelector('form'),mode=f.elements.mode,day=f.elements.day;
  const preview=()=>{day.disabled=mode.value!=='payday';const old=db.settings.payCycle;db.settings.payCycle={mode:mode.value,day:Number(day.value)||25};card.querySelector('#mgwCyclePreview').innerHTML=`<b>Current selection:</b> ${mgwCycleLabel(MGW.state.month)}`;if(old===undefined)delete db.settings.payCycle;else db.settings.payCycle=old};
  mode.addEventListener('change',preview);day.addEventListener('input',preview);preview();f.addEventListener('submit',e=>{e.preventDefault();db.settings.payCycle={mode:mode.value==='payday'?'payday':'calendar',day:Math.min(31,Math.max(1,Number(day.value)||25))};localStorage.setItem(MGW.key,JSON.stringify(db));if(typeof renderAll==='function')renderAll();preview();if(typeof toast==='function')toast(db.settings.payCycle.mode==='payday'?'Pay-cycle tabulation enabled':'Calendar-month tabulation enabled')});
}
function mgwUpdateCycleUI(){const label=document.querySelector('#monthLabel');if(label)label.textContent=mgwCycleLabel(MGW.state.month);const p=document.querySelector('#mgwCyclePreview');if(p)p.innerHTML=`<b>Current period:</b> ${mgwCycleLabel(MGW.state.month)}`;const privacy=document.querySelector('.privacy-note');if(privacy)privacy.textContent='🔒 MoneyGoWhere is local-first. New devices start with an empty database; restore your own backup to move data between devices. Receipt OCR is processed locally in this browser.'}
if(typeof renderAll==='function'){const base=renderAll;renderAll=function(){base();mgwUpdateCycleUI()}}
function mgwExportV15(){const payload={...db,backupMeta:{appVersion:MGW_RUNTIME_RELEASE.appVersion,schemaVersion:MGW_RUNTIME_RELEASE.schemaVersion,dataVersion:MGW_RUNTIME_RELEASE.dataVersion,cacheVersion:MGW_RUNTIME_RELEASE.cacheVersion,exportedAt:new Date().toISOString()}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`MoneyGoWhere-backup-v${MGW_RUNTIME_RELEASE.appVersion}-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);if(typeof toast==='function')toast('Complete backup exported')}

// Load the v1.5 OCR enhancement after the existing app compatibility layers.
const mgwOCRScript=document.createElement('script');mgwOCRScript.src='./ocr-enhance.js';mgwOCRScript.defer=true;document.head.appendChild(mgwOCRScript);

document.addEventListener('DOMContentLoaded',()=>{db.settings=db.settings||{currency:'SGD'};mgwCycleCard();mgwUpdateCycleUI();const badge=document.querySelector('#appVersionBadge');if(badge){badge.textContent=`v${MGW_RUNTIME_RELEASE.appVersion}`;badge.title=`App ${MGW_RUNTIME_RELEASE.appVersion} · Schema ${MGW_RUNTIME_RELEASE.schemaVersion} · Data ${MGW_RUNTIME_RELEASE.dataVersion}`};const exportBtn=document.querySelector('#exportBtn');if(exportBtn)exportBtn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();mgwExportV15()},true);if(typeof renderAll==='function')renderAll()});
