// MoneyGoWhere v1.5.5-dev.12 — first-run onboarding
(()=>{'use strict';
const RELEASE='1.5.5-dev.12',num=v=>Number(v)||0,uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
function saveLocal(){localStorage.setItem(MGW.key,JSON.stringify(db))}
function ensure(){db.settings=db.settings||{};db.settings.onboarding=db.settings.onboarding||{};db.budgets=db.budgets||{monthly:0,categories:{}}}
function css(){if(document.querySelector('#mgwOnboardingCss'))return;const s=document.createElement('style');s.id='mgwOnboardingCss';s.textContent='.mgw-ob{position:fixed;inset:0;z-index:90;background:rgba(15,23,22,.62);display:grid;place-items:center;padding:16px}.mgw-ob-card{width:min(620px,100%);background:#fff;border-radius:24px;padding:22px;max-height:92dvh;overflow:auto}.mgw-ob-progress{height:7px;background:#edf2f1;border-radius:99px;overflow:hidden;margin:12px 0 22px}.mgw-ob-progress i{display:block;height:100%;background:#0f766e}.mgw-ob-actions{display:flex;gap:8px;margin-top:18px}.mgw-ob-actions button{flex:1}';document.head.appendChild(s)}
let state={payday:25,income:'',budget:'',vendor:'',amount:'',category:'Groceries'};
function close(){document.querySelector('#mgwOnboarding')?.remove()}
function show(step=1){let root=document.querySelector('#mgwOnboarding');if(!root){root=document.createElement('div');root.id='mgwOnboarding';root.className='mgw-ob';document.body.appendChild(root)}let body='';if(step===1)body='<h2>Welcome to MoneyGoWhere 👋</h2><p>Budget from payday to payday. Your finance data stays in this browser unless you export it yourself.</p>';if(step===2)body=`<h2>Payday cycle</h2><div class="field"><label>Payday / cycle start day</label><input id="obPay" type="number" min="1" max="31" value="${state.payday}"></div>`;if(step===3)body=`<h2>Main income</h2><div class="field"><label>Typical net income</label><input id="obIncome" type="number" min="0" step="0.01" value="${state.income}"></div>`;if(step===4)body=`<h2>Cycle budget</h2><div class="field"><label>Overall cycle budget</label><input id="obBudget" type="number" min="0" step="0.01" value="${state.budget}"></div>`;if(step===5)body=`<h2>First expense</h2><p>Optional — leave blank to finish without adding one.</p><div class="form-grid"><div class="field"><label>Merchant</label><input id="obVendor" value="${state.vendor}"></div><div class="field"><label>Amount</label><input id="obAmount" type="number" min="0" step="0.01" value="${state.amount}"></div><div class="field full"><label>Category</label><select id="obCat">${Object.keys(MGW.cats).map(c=>`<option ${c===state.category?'selected':''}>${c}</option>`).join('')}</select></div></div>`;root.innerHTML=`<div class="mgw-ob-card"><div class="eyebrow">Setup · Step ${step}/5</div><div class="mgw-ob-progress"><i style="width:${step*20}%"></i></div>${body}<div class="mgw-ob-actions">${step>1?'<button class="secondary-btn" id="obBack">Back</button>':'<button class="secondary-btn" id="obSkip">Skip</button>'}<button class="primary-btn" id="obNext">${step===5?'Finish':'Continue'}</button></div></div>`;root.querySelector('#obBack')?.addEventListener('click',()=>show(step-1));root.querySelector('#obSkip')?.addEventListener('click',()=>{db.settings.onboarding.skippedAt=new Date().toISOString();saveLocal();close()});root.querySelector('#obNext').addEventListener('click',()=>{if(step===2)state.payday=Math.min(31,Math.max(1,Number(root.querySelector('#obPay').value)||25));if(step===3)state.income=root.querySelector('#obIncome').value;if(step===4)state.budget=root.querySelector('#obBudget').value;if(step===5){state.vendor=root.querySelector('#obVendor').value.trim();state.amount=root.querySelector('#obAmount').value;state.category=root.querySelector('#obCat').value;finish();return}show(step+1)})}
function finish(){db.settings.payCycle={mode:'payday',day:state.payday};db.settings.paydayConfig={dayOfMonth:state.payday,frequency:'monthly',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'local'};if(num(state.income)>0)db.income.push({id:uid('INC'),date:new Date().toISOString().slice(0,10),baseSalary:num(state.income),netSalary:num(state.income),bonus:0,oneOff:0,source:'onboarding'});if(num(state.budget)>0)db.budgets.monthly=num(state.budget);if(state.vendor&&num(state.amount)>0)db.expenses.push({id:uid('EXP'),date:new Date().toISOString().slice(0,10),time:'',vendor:state.vendor,amount:num(state.amount),currency:db.settings.currency||'SGD',category:state.category,source:'onboarding'});db.settings.onboarding={completed:true,completedAt:new Date().toISOString()};saveLocal();close();if(typeof renderAll==='function')renderAll();if(typeof toast==='function')toast('Setup complete')}
function installSettings(){const view=document.querySelector('#view-settings');if(!view||document.querySelector('#mgwOnboardingSettings'))return;const card=document.createElement('article');card.className='card';card.id='mgwOnboardingSettings';card.innerHTML='<div class="card-head"><div><span class="section-icon">👋</span><b>Welcome Setup</b></div></div><button class="secondary-btn" id="mgwRunOnboarding">Run setup again</button>';view.insertBefore(card,view.querySelector('.privacy-note')||null);card.querySelector('#mgwRunOnboarding').addEventListener('click',()=>show(1))}
function refresh(){ensure();installSettings();document.querySelectorAll('.budget-card .card-head b').forEach(b=>{if(/monthly budget/i.test(b.textContent))b.textContent='Cycle Budget'});const badge=document.querySelector('#mgwRuntimeVersionBadge');if(badge){badge.textContent=`v${RELEASE} · DEV`;badge.title='Development build with onboarding'}}
function recoverWallet(){const m=document.querySelector('#modal'),f=document.querySelector('#expenseForm');if(!m?.open||!f||!/apple\s*pay/i.test(f.elements.paymentMethod?.value||''))return;db.importQueue=Array.isArray(db.importQueue)?db.importQueue:[];const merchant=String(f.elements.vendor?.value||'').trim(),amount=num(f.elements.amount?.value),date=String(f.elements.date?.value||'').slice(0,10),time=String(f.elements.time?.value||'').slice(0,5),card=String(f.elements.card?.value||'').trim();if(!merchant||amount<=0)return;const sourceId=`wallet-${date}-${time}-${amount}-${merchant}-${card}`;if(!db.importQueue.some(x=>x.sourceId===sourceId))db.importQueue.push({id:uid('IMP'),source:'apple_wallet',sourceId,merchant,amount,date,time,currency:'SGD',card,paymentMethod:'Apple Pay',category:'',confidence:0,status:'pending'});saveLocal();try{m.close()}catch{}if(typeof renderAll==='function')renderAll();if(typeof nav==='function')nav('add');if(typeof toast==='function')toast('Wallet transaction queued for review')}
function boot(){ensure();css();refresh();if(typeof renderAll==='function'&&!renderAll.__mgwOnboarding){const base=renderAll;renderAll=function(){base();queueMicrotask(refresh)};renderAll.__mgwOnboarding=true}if(!db.settings.onboarding.completed&&!db.expenses.length&&!db.income.length)setTimeout(()=>show(1),200);setTimeout(recoverWallet,50);setTimeout(recoverWallet,350);setTimeout(recoverWallet,900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.MGWOnboarding={version:RELEASE,run:()=>show(1)};})();