// MoneyGoWhere DEV — salary progression insights
// Local-first: reads only the user's local income records at runtime.
(()=>{
'use strict';
const RELEASE='1.5.5-dev.21';
const num=v=>Number(v)||0;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let range='all';
function rows(){return [...(db?.income||[])].filter(x=>x?.date).sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function filtered(){const all=rows();if(range==='all')return all;const months=range==='12m'?12:36;if(!all.length)return all;const end=new Date();const start=new Date(end.getFullYear(),end.getMonth()-months+1,1);return all.filter(x=>{const d=new Date(String(x.date).slice(0,10)+'T00:00:00');return !Number.isNaN(d.getTime())&&d>=start})}
function pct(a,b){return a?((b-a)/a*100):0}
function moneyText(v){return typeof money==='function'?money(v):new Intl.NumberFormat('en-SG',{style:'currency',currency:db?.settings?.currency||'SGD'}).format(num(v))}
function shortMoney(v){const n=num(v);if(n>=1000)return `${(n/1000).toFixed(n>=10000?0:1)}k`;return n.toFixed(0)}
function installStyles(){if(document.querySelector('#mgwSalaryTrendStyles'))return;const s=document.createElement('style');s.id='mgwSalaryTrendStyles';s.textContent=`
#mgwSalaryProgression{display:grid;gap:12px}.mgw-income-section-title{display:flex;align-items:center;gap:8px;margin:2px 0 0}.mgw-income-section-title b{font-size:1rem}.mgw-income-section-title small{opacity:.62}.mgw-salary-toolbar{display:flex;gap:6px;flex-wrap:wrap}.mgw-salary-toolbar button{border:1px solid var(--border,#dbe4e4);background:transparent;border-radius:999px;padding:7px 10px}.mgw-salary-toolbar button.active{background:var(--accent,#128277);color:#fff;border-color:transparent}.mgw-salary-kpis{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.mgw-salary-kpi{padding:10px;border-radius:12px;background:rgba(18,130,119,.055)}.mgw-salary-kpi small,.mgw-salary-kpi strong{display:block}.mgw-salary-kpi strong{margin-top:3px}.mgw-salary-chart{overflow-x:auto;padding:4px 0 6px}.mgw-salary-bars{display:flex;align-items:end;gap:12px;min-height:225px;min-width:max-content;padding:10px 4px 0}.mgw-salary-point{width:76px;text-align:center}.mgw-salary-value{font-size:.68rem;font-weight:800;white-space:nowrap;margin-bottom:4px}.mgw-salary-pair{height:120px;display:flex;align-items:end;justify-content:center;gap:5px}.mgw-salary-bar{width:18px;min-height:3px;border-radius:6px 6px 2px 2px;background:var(--accent,#128277)}.mgw-salary-bar.net{opacity:.42}.mgw-salary-point>small{display:block;font-size:.68rem;opacity:.65;margin-top:5px;white-space:nowrap}.mgw-salary-numbers{display:grid;gap:2px;margin-top:4px;font-size:.65rem;line-height:1.2}.mgw-salary-numbers b{font-weight:700}.mgw-salary-numbers span{opacity:.62}.mgw-salary-legend{display:flex;gap:14px;font-size:.78rem;opacity:.75}.mgw-salary-legend span:before{content:'';display:inline-block;width:9px;height:9px;border-radius:2px;background:var(--accent,#128277);margin-right:5px}.mgw-salary-legend span:last-child:before{opacity:.42}.mgw-salary-steps{display:grid;gap:7px}.mgw-salary-step{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:9px 0;border-top:1px solid var(--border,#eef1f1)}.mgw-salary-step small{display:block;opacity:.65;margin-top:2px}.mgw-salary-up{font-weight:800}.mgw-salary-empty{padding:12px 0;opacity:.7}.mgw-bonus-panel{margin-top:14px;padding-top:14px;border-top:1px solid var(--border,#e7ecec)}.mgw-bonus-years{display:grid;gap:8px;margin-top:10px}.mgw-bonus-year{border:1px solid var(--border,#e3e9e9);border-radius:12px;overflow:hidden}.mgw-bonus-year>summary{list-style:none;cursor:pointer;display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:10px 12px}.mgw-bonus-year>summary::-webkit-details-marker{display:none}.mgw-bonus-year small{display:block;opacity:.65;margin-top:2px}.mgw-bonus-detail{padding:2px 12px 8px;border-top:1px solid var(--border,#edf1f1)}.mgw-bonus-line{display:grid;grid-template-columns:1fr auto;gap:10px;padding:8px 0;border-bottom:1px solid var(--border,#f0f3f3)}.mgw-bonus-line:last-child{border-bottom:0}@media(min-width:700px){.mgw-salary-kpis{grid-template-columns:repeat(4,minmax(0,1fr))}}
`;document.head.appendChild(s)}
function renderBonus(host,all){
  if(!host)return;
  const bonusRows=all.filter(x=>num(x.bonus)>0);
  const years=new Map();for(const x of bonusRows){const y=String(x.date).slice(0,4)||'Unknown';if(!years.has(y))years.set(y,[]);years.get(y).push(x)}
  const content=[...years.entries()].sort((a,b)=>b[0].localeCompare(a[0])).map(([y,list])=>{const total=list.reduce((t,x)=>t+num(x.bonus),0);return `<details class="mgw-bonus-year"><summary><div><b>${esc(y)} Bonus</b><small>${list.length} ${list.length===1?'payment':'payments'}</small></div><strong>${moneyText(total)}</strong></summary><div class="mgw-bonus-detail">${list.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=>`<div class="mgw-bonus-line"><span>${esc(String(x.date).slice(0,10))}</span><strong>${moneyText(x.bonus)}</strong></div>`).join('')}</div></details>`}).join('');
  host.className='mgw-bonus-panel';host.innerHTML=`<div class="mgw-income-section-title"><span>🎁</span><div><b>Bonus History</b><small>Grouped separately from monthly salary</small></div></div><div class="mgw-bonus-years">${content||'<p class="mgw-salary-empty">No bonus records yet.</p>'}</div>`;
}
function render(){
  const host=document.querySelector('#salaryTrend');if(!host)return;installStyles();const data=filtered(),all=rows(),bonus=document.querySelector('#bonusHistory');
  const parent=host.closest('.card');const head=parent?.querySelector('.card-head b');if(head)head.textContent='Income Trends';
  if(!data.length){host.className='';host.innerHTML='<div id="mgwSalaryProgression"><div class="mgw-income-section-title"><span>💼</span><div><b>Salary Progression</b><small>Base and net salary</small></div></div><p class="mgw-salary-empty">Add income records to build your salary progression.</p></div>';renderBonus(bonus,all);return}
  const vals=data.map(x=>Math.max(num(x.baseSalary),num(x.netSalary))),max=Math.max(...vals,1),first=all[0]||data[0],latest=all.at(-1)||data.at(-1),baseGrowth=pct(num(first.baseSalary),num(latest.baseSalary)),netGrowth=pct(num(first.netSalary),num(latest.netSalary));
  const stepRows=[];let prev=null;for(const x of all){const b=num(x.baseSalary);if(b>0&&prev!==null&&b!==prev)stepRows.push({date:x.date,from:prev,to:b,change:pct(prev,b)});if(b>0)prev=b}
  const points=data.map(x=>{const d=new Date(String(x.date).slice(0,10)+'T00:00:00'),label=Number.isNaN(d.getTime())?String(x.date).slice(0,7):d.toLocaleDateString('en-SG',{month:'short',year:'2-digit'}),bh=Math.max(3,num(x.baseSalary)/max*120),nh=Math.max(3,num(x.netSalary)/max*120);return `<div class="mgw-salary-point" title="${esc(label)} · Base ${esc(moneyText(x.baseSalary))} · Net ${esc(moneyText(x.netSalary))}"><div class="mgw-salary-value">${esc(shortMoney(Math.max(num(x.baseSalary),num(x.netSalary))))}</div><div class="mgw-salary-pair"><i class="mgw-salary-bar" style="height:${bh}px"></i><i class="mgw-salary-bar net" style="height:${nh}px"></i></div><small>${esc(label)}</small><div class="mgw-salary-numbers"><b>Base ${esc(moneyText(x.baseSalary))}</b><span>Net ${esc(moneyText(x.netSalary))}</span></div></div>`}).join('');
  host.className='';host.innerHTML=`<div id="mgwSalaryProgression"><div class="mgw-income-section-title"><span>💼</span><div><b>Salary Progression</b><small>Exact values with base vs net bars</small></div></div><div class="mgw-salary-toolbar"><button data-salary-range="12m" class="${range==='12m'?'active':''}">12 Months</button><button data-salary-range="3y" class="${range==='3y'?'active':''}">3 Years</button><button data-salary-range="all" class="${range==='all'?'active':''}">All Time</button></div><div class="mgw-salary-kpis"><div class="mgw-salary-kpi"><small>Current base</small><strong>${moneyText(latest.baseSalary)}</strong></div><div class="mgw-salary-kpi"><small>Current net</small><strong>${moneyText(latest.netSalary)}</strong></div><div class="mgw-salary-kpi"><small>Base growth</small><strong>${baseGrowth>=0?'+':''}${baseGrowth.toFixed(1)}%</strong></div><div class="mgw-salary-kpi"><small>Net growth</small><strong>${netGrowth>=0?'+':''}${netGrowth.toFixed(1)}%</strong></div></div><div class="mgw-salary-legend"><span>Base salary</span><span>Net salary</span></div><div class="mgw-salary-chart"><div class="mgw-salary-bars">${points}</div></div>${stepRows.length?`<div><b>Salary change history</b><div class="mgw-salary-steps">${stepRows.slice().reverse().map(x=>`<div class="mgw-salary-step"><div><b>${moneyText(x.from)} → ${moneyText(x.to)}</b><small>${esc(String(x.date).slice(0,10))}</small></div><span class="mgw-salary-up">${x.change>=0?'+':''}${x.change.toFixed(1)}%</span></div>`).join('')}</div></div>`:''}</div>`;
  host.querySelectorAll('[data-salary-range]').forEach(b=>b.addEventListener('click',()=>{range=b.dataset.salaryRange;render()}));renderBonus(bonus,all);
}
function boot(){if(typeof renderAll==='function'&&!renderAll.__mgwSalaryTrends){const base=renderAll;renderAll=function(){base();queueMicrotask(render)};renderAll.__mgwSalaryTrends=true}render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.MGWSalaryTrends={version:RELEASE,render};
})();