// MoneyGoWhere DEV — salary progression insights
// Local-first: reads only the user's local income records at runtime.
(()=>{
'use strict';
const RELEASE='1.5.5-dev.20';
const num=v=>Number(v)||0;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let range='all';
function rows(){return [...(db?.income||[])].filter(x=>x?.date).sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function filtered(){const all=rows();if(range==='all')return all;const months=range==='12m'?12:36;if(!all.length)return all;const end=new Date();const start=new Date(end.getFullYear(),end.getMonth()-months+1,1);return all.filter(x=>{const d=new Date(String(x.date).slice(0,10)+'T00:00:00');return !Number.isNaN(d.getTime())&&d>=start})}
function pct(a,b){return a?((b-a)/a*100):0}
function moneyText(v){return typeof money==='function'?money(v):new Intl.NumberFormat('en-SG',{style:'currency',currency:db?.settings?.currency||'SGD'}).format(num(v))}
function installStyles(){if(document.querySelector('#mgwSalaryTrendStyles'))return;const s=document.createElement('style');s.id='mgwSalaryTrendStyles';s.textContent=`
#mgwSalaryProgression{display:grid;gap:12px}.mgw-salary-toolbar{display:flex;gap:6px;flex-wrap:wrap}.mgw-salary-toolbar button{border:1px solid var(--border,#dbe4e4);background:transparent;border-radius:999px;padding:7px 10px}.mgw-salary-toolbar button.active{background:var(--accent,#128277);color:#fff;border-color:transparent}.mgw-salary-kpis{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.mgw-salary-kpi{padding:10px;border-radius:12px;background:rgba(18,130,119,.055)}.mgw-salary-kpi small,.mgw-salary-kpi strong{display:block}.mgw-salary-kpi strong{margin-top:3px}.mgw-salary-chart{overflow-x:auto;padding-bottom:4px}.mgw-salary-bars{display:flex;align-items:end;gap:9px;min-height:175px;min-width:max-content;padding:10px 2px 0}.mgw-salary-point{width:46px;text-align:center}.mgw-salary-pair{height:120px;display:flex;align-items:end;justify-content:center;gap:4px}.mgw-salary-bar{width:14px;min-height:3px;border-radius:6px 6px 2px 2px;background:var(--accent,#128277)}.mgw-salary-bar.net{opacity:.42}.mgw-salary-point small{display:block;font-size:.68rem;opacity:.65;margin-top:5px;white-space:nowrap}.mgw-salary-legend{display:flex;gap:14px;font-size:.78rem;opacity:.75}.mgw-salary-legend span:before{content:'';display:inline-block;width:9px;height:9px;border-radius:2px;background:var(--accent,#128277);margin-right:5px}.mgw-salary-legend span:last-child:before{opacity:.42}.mgw-salary-steps{display:grid;gap:7px}.mgw-salary-step{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:9px 0;border-top:1px solid var(--border,#eef1f1)}.mgw-salary-step small{display:block;opacity:.65;margin-top:2px}.mgw-salary-up{font-weight:800}.mgw-salary-empty{padding:12px 0;opacity:.7}@media(min-width:700px){.mgw-salary-kpis{grid-template-columns:repeat(4,minmax(0,1fr))}}
`;document.head.appendChild(s)}
function render(){
  const host=document.querySelector('#salaryTrend');if(!host)return;installStyles();const data=filtered(),all=rows();
  const bonus=document.querySelector('#bonusHistory');
  if(!data.length){host.className='';host.innerHTML='<div id="mgwSalaryProgression"><p class="mgw-salary-empty">Add income records to build your salary progression.</p></div>';return}
  const vals=data.map(x=>Math.max(num(x.baseSalary),num(x.netSalary))),max=Math.max(...vals,1),first=all[0]||data[0],latest=all.at(-1)||data.at(-1),baseGrowth=pct(num(first.baseSalary),num(latest.baseSalary)),netGrowth=pct(num(first.netSalary),num(latest.netSalary));
  const stepRows=[];let prev=null;for(const x of all){const b=num(x.baseSalary);if(b>0&&prev!==null&&b!==prev)stepRows.push({date:x.date,from:prev,to:b,change:pct(prev,b)});if(b>0)prev=b}
  const points=data.map(x=>{const d=new Date(String(x.date).slice(0,10)+'T00:00:00'),label=Number.isNaN(d.getTime())?String(x.date).slice(0,7):d.toLocaleDateString('en-SG',{month:'short',year:'2-digit'}),bh=Math.max(3,num(x.baseSalary)/max*120),nh=Math.max(3,num(x.netSalary)/max*120);return `<div class="mgw-salary-point" title="${esc(label)} · Base ${esc(moneyText(x.baseSalary))} · Net ${esc(moneyText(x.netSalary))}"><div class="mgw-salary-pair"><i class="mgw-salary-bar" style="height:${bh}px"></i><i class="mgw-salary-bar net" style="height:${nh}px"></i></div><small>${esc(label)}</small></div>`}).join('');
  host.className='';host.innerHTML=`<div id="mgwSalaryProgression"><div class="mgw-salary-toolbar"><button data-salary-range="12m" class="${range==='12m'?'active':''}">12 Months</button><button data-salary-range="3y" class="${range==='3y'?'active':''}">3 Years</button><button data-salary-range="all" class="${range==='all'?'active':''}">All Time</button></div><div class="mgw-salary-kpis"><div class="mgw-salary-kpi"><small>Current base</small><strong>${moneyText(latest.baseSalary)}</strong></div><div class="mgw-salary-kpi"><small>Current net</small><strong>${moneyText(latest.netSalary)}</strong></div><div class="mgw-salary-kpi"><small>Base growth</small><strong>${baseGrowth>=0?'+':''}${baseGrowth.toFixed(1)}%</strong></div><div class="mgw-salary-kpi"><small>Net growth</small><strong>${netGrowth>=0?'+':''}${netGrowth.toFixed(1)}%</strong></div></div><div class="mgw-salary-legend"><span>Base salary</span><span>Net salary</span></div><div class="mgw-salary-chart"><div class="mgw-salary-bars">${points}</div></div>${stepRows.length?`<div><b>Salary progression</b><div class="mgw-salary-steps">${stepRows.slice().reverse().map(x=>`<div class="mgw-salary-step"><div><b>${moneyText(x.from)} → ${moneyText(x.to)}</b><small>${esc(String(x.date).slice(0,10))}</small></div><span class="mgw-salary-up">${x.change>=0?'+':''}${x.change.toFixed(1)}%</span></div>`).join('')}</div></div>`:''}</div>`;
  host.querySelectorAll('[data-salary-range]').forEach(b=>b.addEventListener('click',()=>{range=b.dataset.salaryRange;render()}));
  if(bonus)bonus.previousElementSibling?.classList?.add?.('mgw-bonus-separator');
}
function boot(){if(typeof renderAll==='function'&&!renderAll.__mgwSalaryTrends){const base=renderAll;renderAll=function(){base();queueMicrotask(render)};renderAll.__mgwSalaryTrends=true}render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.MGWSalaryTrends={version:RELEASE,render};
})();