// Stable Settings groups. Existing elements are moved, retaining their handlers and data IDs.
(()=>{'use strict';
const GROUPS=[['wallet','My Wallet'],['budget','Budget & Tracking'],['recurring','Recurring Payments'],['debt','Debt & Pay-Later'],['imports','Receipts & Imports'],['maintenance','Backup & Maintenance']];
const CARDS={wallet:['mgwUnifiedWallet'],budget:['mgwBudgetActions','mgwPayCycleCard'],recurring:['mgwRecurringSettings','mgwCommitmentSettings','mgwRecurringBillsSettings','mgwOtherRecurring','mgwPausedRecurring','mgwRecurringReview'],debt:['mgwCreditSettings'],imports:['mgwImportActions','mgwWalletSettings'],maintenance:['mgwBackupActions','mgwDbHealthCard','mgwReleaseReadiness','mgwOnboardingSettings','mgwWalkSettings']};
const IMPORT_ROWS=['mgwScanApplePayFolderSettings','mgwRunStartupImport'];
const PREF='mgw-settings-sections-v1';let queued=false;
function preference(database){database.settings=database.settings||{};const settings=database.settings;const p=settings.startupImport=settings.startupImport&&typeof settings.startupImport==='object'?settings.startupImport:{};if(p.preferenceVersion!==1){p.enabled=false;p.preferenceVersion=1}return p}
function saved(){try{return JSON.parse(localStorage.getItem(PREF)||'{}')||{}}catch{return {}}}
function move(node,host){if(node&&host&&node.parentElement!==host)host.appendChild(node)}
async function imports(action){try{await window.MGWLoadImportFeatures?.();refresh();if(action==='startup')window.MGWStartupImport?.startup();else if(action==='receipt')window.MGWStartupImport?.selectReceipts();else if(action==='review'){window.nav?.('add');document.querySelector('#mgwWalletImportQueue,#mgwReceiptBatchQueue')?.scrollIntoView({block:'start'})}else if(action==='check')window.MGWStartupImport?.show()}catch(err){console.error('MoneyGoWhere import controls failed',err);window.toast?.('Could not load import tools. Please try again.')}}
function actionCard(id){let node=document.getElementById(id);if(!node){node=document.createElement('article');node.id=id;node.className='card mgw-settings-actions'}return node}
function refresh(){
 const view=document.getElementById('view-settings');if(!view)return;
 const prefs=saved(),bodies={};
 for(const [key,title] of GROUPS){let group=document.getElementById('mgwSettings-'+key);if(!group){group=document.createElement('details');group.id='mgwSettings-'+key;group.dataset.settingsSection=group.id;group.className='mgw-settings-group';group.open=prefs[group.id]??(key!=='imports');const summary=document.createElement('summary');summary.textContent=title;const body=document.createElement('div');body.className='mgw-settings-group-body';group.append(summary,body);view.insertBefore(group,[...view.children].find(x=>x.classList.contains('privacy-note'))||null);group.addEventListener('toggle',()=>{const next=saved();next[group.id]=group.open;try{localStorage.setItem(PREF,JSON.stringify(next))}catch{}if(key==='imports'&&group.open)imports()})}bodies[key]=group.querySelector('.mgw-settings-group-body')}
 const legacy=view.querySelector('.settings-list');if(legacy)legacy.id='mgwBackupActions';
 const budget=actionCard('mgwBudgetActions');move(view.querySelector('[data-open="budget"]'),budget);move(budget,bodies.budget);
 let controls=document.getElementById('mgwImportActions');if(!controls){controls=actionCard('mgwImportActions');controls.innerHTML='<button type="button" id="mgwImportReceiptImages"><span>🧾</span><div><b>Import Receipts</b><small>Select receipt images and review scanned details</small></div><i>›</i></button><button type="button" id="mgwReviewPendingImports"><span>📥</span><div><b>Review Pending Imports</b><small>Review receipt and Apple Pay transactions before saving</small></div><i>›</i></button><button type="button" id="mgwStartupImportToggle" role="switch" aria-checked="false"><span>⚙️</span><div><b>Show import prompt at startup</b><small>Ask to import receipts or Apple Pay transactions when MGW opens</small></div><span data-startup-state>Off</span></button>';controls.querySelector('#mgwImportReceiptImages').addEventListener('click',()=>imports('receipt'));controls.querySelector('#mgwReviewPendingImports').addEventListener('click',()=>imports('review'));controls.querySelector('#mgwStartupImportToggle').addEventListener('click',()=>{if(!window.db)return;const p=preference(window.db),next=!p.enabled;try{const copy=JSON.parse(JSON.stringify(window.db));preference(copy).enabled=next;localStorage.setItem(window.MGW?.key||'moneygowhere-db-v1',JSON.stringify(copy));p.enabled=next;refresh()}catch(err){window.toast?.('Could not save the startup preference')}})}
 move(controls,bodies.imports);
 if(window.db){const p=preference(window.db),toggle=controls.querySelector('#mgwStartupImportToggle');toggle.setAttribute('aria-checked',String(p.enabled===true));const label=toggle.querySelector('[data-startup-state]');if(label.textContent!==(p.enabled?'On':'Off'))label.textContent=p.enabled?'On':'Off'}
 for(const id of IMPORT_ROWS)move(document.getElementById(id),controls);
 // Locate by ID even when a lazy module inserted a card beside an already nested card.
 for(const [key,ids] of Object.entries(CARDS))for(const id of ids){const card=document.getElementById(id);if(!card)continue;const old=card.parentElement?.matches('details.mgw-settings-section')?card.parentElement:null;if(id==='mgwPausedRecurring'){let nested=old;if(!nested){nested=document.createElement('details');nested.className='mgw-settings-section';nested.dataset.settingsSection=id;nested.open=prefs[id]!==false;const summary=document.createElement('summary');summary.textContent='Paused Recurring';nested.append(summary,card);nested.addEventListener('toggle',()=>{const next=saved();next[id]=nested.open;try{localStorage.setItem(PREF,JSON.stringify(next))}catch{}})}move(nested,bodies[key])}else{move(card,bodies[key]);if(old&&!old.querySelector('article'))old.remove()}}
 // Keep card ordering independent of lazy-module load order without replacing nodes.
 for(const [key,ids] of Object.entries(CARDS)){let index=0;for(const id of ids){const card=document.getElementById(id);if(!card)continue;const node=id==='mgwPausedRecurring'?card.parentElement:card;if(bodies[key].children[index]!==node)bodies[key].insertBefore(node,bodies[key].children[index]||null);index++}}
 // Unknown optional cards remain accessible in maintenance.
 for(const card of [...view.children].filter(x=>x.matches('article.card')))move(card,bodies.maintenance);
}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;refresh()})}
function boot(){refresh();const view=document.getElementById('view-settings');if(view&&typeof MutationObserver==='function')new MutationObserver(records=>{if(records.some(r=>r.addedNodes.length||r.removedNodes.length))schedule()}).observe(view,{childList:true,subtree:true});for(const event of ['mgw:data-ready','mgw:data-restored','mgw:settings-features-ready','mgw:import-features-ready','mgw:wallet-rendered'])document.addEventListener(event,schedule);document.addEventListener('mgw:app-ready',()=>{schedule();if(window.db&&preference(window.db).enabled===true)imports('startup')},{once:true})}
window.MGWSettingsLayout=Object.freeze({refresh,preference,groups:GROUPS.map(([key,title])=>({key,title})),cards:CARDS});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
