// MoneyGoWhere DEV — lazy purchase history + edit/delete historical transactions.
(()=>{'use strict';
const RELEASE=window.MGW_RELEASE?.appVersion||'dev';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v)||0;
const norm=v=>String(v||'').replace(/^[^A-Za-z0-9]+/,'').trim().replace(/\s+/g,' ').toUpperCase();
const persist=()=>localStorage.setItem(MGW.key,JSON.stringify(db));
const merchant=x=>String(x.vendor||x.merchant||x.notes||x.category||'Other').trim()||'Other';
const monthLabel=key=>{const [y,m]=String(key).split('-').map(Number),d=new Date(y,m-1,1);return Number.isNaN(d.getTime())?key:d.toLocaleDateString('en-SG',{month:'long',year:'numeric'})};
let historyDirty=true,painting=false;
function catsOptions(sel=''){return '<option value="">Select category</option>'+Object.keys(MGW.cats).map(c=>`<option value="${esc(c)}" ${c===sel?'selected':''}>${esc(c)}</option>`).join('')}
function styles(){if(document.querySelector('#mgwTxEditorCss'))return;const s=document.createElement('style');s.id='mgwTxEditorCss';s.textContent=`
.mgw-tx-actions{display:flex;gap:6px;justify-content:flex-end;margin-top:6px}.mgw-tx-actions button{border:0;border-radius:9px;padding:6px 9px;font-size:.76rem;font-weight:800;cursor:pointer}.mgw-tx-edit{background:var(--brand-soft,#e8f5f2);color:var(--brand,#0f766e)}.mgw-tx-delete{background:#fff1f2;color:#be123c}
.mgw-swipe-row{position:relative;overflow:hidden;border-bottom:1px solid var(--line,#e4e9e7);touch-action:pan-y}.mgw-swipe-row:last-child{border-bottom:0}.mgw-swipe-actions{position:absolute;inset:0 0 0 auto;width:144px;display:grid;grid-template-columns:1fr 1fr}.mgw-swipe-actions button{border:0;border-radius:0;color:#fff;font-size:.72rem;font-weight:900}.mgw-swipe-actions .mgw-tx-edit{background:var(--brand,#0f766e);color:#fff}.mgw-swipe-actions .mgw-tx-delete{background:#be123c;color:#fff}.mgw-swipe-content{position:relative;z-index:1;background:#fff;transform:translate3d(0,0,0);transition:transform .18s ease;will-change:transform}.mgw-swipe-row.is-open .mgw-swipe-content{transform:translate3d(-144px,0,0)}.mgw-swipe-content.tx{border-bottom:0;padding:10px 0}.mgw-swipe-hint{font-size:.68rem;color:var(--muted,#6b7774);white-space:nowrap}

#mgwPurchaseHistory .mgw-history-list{display:grid;gap:9px}.mgw-history-month,.mgw-history-merchant{border:1px solid var(--line,#e4e9e7);border-radius:14px;overflow:hidden;background:#fff}.mgw-history-month>summary,.mgw-history-merchant>summary{list-style:none;cursor:pointer;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center}.mgw-history-month>summary{padding:13px 14px;background:rgba(15,118,110,.045)}.mgw-history-merchant>summary{padding:11px 12px}.mgw-history-month>summary::-webkit-details-marker,.mgw-history-merchant>summary::-webkit-details-marker{display:none}.mgw-history-copy{min-width:0}.mgw-history-copy b,.mgw-history-copy small{display:block;overflow-wrap:anywhere}.mgw-history-copy small{margin-top:2px;color:var(--muted,#6b7774)}.mgw-history-right{display:flex;align-items:center;gap:8px;white-space:nowrap;text-align:right}.mgw-history-month-body{padding:8px;display:grid;gap:7px;border-top:1px solid var(--line,#e4e9e7)}.mgw-history-merchant-body{padding:0 11px 8px;border-top:1px solid var(--line,#e4e9e7)}.mgw-history-line{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px 12px;padding:10px 0;border-bottom:1px solid var(--line,#eef2f1);align-items:start}.mgw-history-line:last-child{border-bottom:0}.mgw-history-line b,.mgw-history-line small{display:block;overflow-wrap:anywhere}.mgw-history-line small{margin-top:2px;color:var(--muted,#6b7774);font-size:.78rem}.mgw-history-line>strong{white-space:nowrap}.mgw-history-line .mgw-tx-actions{grid-column:1/-1;justify-content:flex-start;margin-top:0}.mgw-history-loading{padding:18px 0;color:var(--muted,#6b7774)}
@media(max-width:520px){.mgw-tx-actions button{padding:7px 10px}.mgw-history-month>summary,.mgw-history-merchant>summary{grid-template-columns:minmax(0,1fr) auto}.mgw-history-right strong{font-size:.9rem}.mgw-history-line{grid-template-columns:minmax(0,1fr) auto}}
`;document.head.appendChild(s)}
function actionButtons(id){return `<div class="mgw-tx-actions"><button type="button" class="mgw-tx-edit" data-edit-expense="${esc(id)}">Edit</button><button type="button" class="mgw-tx-delete" data-delete-expense="${esc(id)}">Delete</button></div>`}
function renderRecent(){const el=document.querySelector('#recentTransactions');if(!el)return;const rows=[...(db.expenses||[])].sort((a,b)=>String((b.date||'')+(b.time||'')).localeCompare(String((a.date||'')+(a.time||'')))).slice(0,12);if(!rows.length){el.className='transaction-list empty-state';el.textContent='Nothing recorded yet.';return}el.className='transaction-list';el.innerHTML=rows.map(x=>`<div class="mgw-swipe-row" data-expense-id="${esc(x.id||'')}"><div class="mgw-swipe-actions"><button type="button" class="mgw-tx-edit" data-edit-expense="${esc(x.id||'')}">✏️<br>Edit</button><button type="button" class="mgw-tx-delete" data-delete-expense="${esc(x.id||'')}">🗑️<br>Delete</button></div><div class="mgw-swipe-content tx"><span class="cat-icon">${MGW.cats[x.category]||'📦'}</span><div><b>${esc(x.vendor||x.category||'Expense')}</b><small>${esc(String(x.date||''))}${x.location?' · '+esc(x.location):''}</small></div><div><span class="amount">${money(x.amount)}</span><small class="mgw-swipe-hint">Swipe left</small></div></div></div>`).join('')}
function historyLine(x){const meta=[String(x.date||'').slice(0,10),x.time,x.location,x.notes].filter(Boolean).join(' · ');return `<div class="mgw-history-line" data-expense-id="${esc(x.id||'')}"><div><b>${esc(merchant(x))}</b><small>${esc(meta)}</small></div><strong>${money(num(x.amount))}</strong>${actionButtons(x.id||'')}</div>`}
function groupedRows(rows){const map=new Map();for(const x of rows){const name=merchant(x),k=norm(name);if(!map.has(k))map.set(k,{name,rows:[]});map.get(k).rows.push(x)}return [...map.values()].map(g=>{g.rows.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(b.time||'').localeCompare(String(a.time||'')));if(g.rows.length===1)return historyLine(g.rows[0]);const total=g.rows.reduce((t,x)=>t+num(x.amount),0);return `<details class="mgw-history-merchant"><summary><div class="mgw-history-copy"><b>${esc(g.name)}</b><small>${g.rows.length} purchases</small></div><div class="mgw-history-right"><strong>${money(total)}</strong><i class="mgw-ui-chevron">›</i></div></summary><div class="mgw-history-merchant-body">${g.rows.map(historyLine).join('')}</div></details>`}).join('')}
function ensureHistoryCard(){const view=document.querySelector('#view-insights');if(!view)return null;let card=document.querySelector('#mgwPurchaseHistory');if(!card){card=document.createElement('article');card.className='card';card.id='mgwPurchaseHistory';card.innerHTML='<div class="card-head"><div><span class="section-icon">🧾</span><b>Purchase History</b></div></div><div class="mgw-history-loading">Open Insights to load purchase history.</div>';view.appendChild(card)}return card}
function renderHistory(force=false){const view=document.querySelector('#view-insights'),card=ensureHistoryCard();if(!view||!card)return;if(!force&&!view.classList.contains('active')){historyDirty=true;return}if(!historyDirty&&!force)return;historyDirty=false;const rows=[...(db.expenses||[])].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(b.time||'').localeCompare(String(a.time||'')));const months=new Map();for(const x of rows){const k=String(x.date||'').slice(0,7)||'Unknown';if(!months.has(k))months.set(k,[]);months.get(k).push(x)}const body=[...months.entries()].sort((a,b)=>b[0].localeCompare(a[0])).map(([k,list])=>`<details class="mgw-history-month"><summary><div class="mgw-history-copy"><b>${esc(monthLabel(k))}</b><small>${list.length} ${list.length===1?'purchase':'purchases'}</small></div><div class="mgw-history-right"><strong>${money(list.reduce((t,x)=>t+num(x.amount),0))}</strong><i class="mgw-ui-chevron">›</i></div></summary><div class="mgw-history-month-body">${groupedRows(list)}</div></details>`).join('');card.innerHTML=`<div class="card-head"><div><span class="section-icon">🧾</span><b>Purchase History</b></div></div><p class="mgw-muted">Browse historical purchases by month. Edit or delete only when needed.</p><div class="mgw-history-list">${body||'<p class="empty-state">No purchase history yet.</p>'}</div>`}
function findExpense(id){return (db.expenses||[]).find(x=>String(x.id)===String(id))}
function editorForm(x){return `<form id="mgwEditExpenseForm" class="form-grid"><div class="field"><label>Date</label><input name="date" type="date" required value="${esc(String(x.date||'').slice(0,10))}"></div><div class="field"><label>Time</label><input name="time" type="time" value="${esc(x.time||'')}"></div><div class="field"><label>Vendor</label><input name="vendor" value="${esc(x.vendor||x.merchant||'')}"></div><div class="field"><label>Location</label><input name="location" value="${esc(x.location||'')}"></div><div class="field"><label>Amount</label><input name="amount" type="number" min="0" step="0.01" required value="${esc(x.amount)}"></div><div class="field"><label>Currency</label><select name="currency"><option ${String(x.currency||'SGD')==='SGD'?'selected':''}>SGD</option><option ${x.currency==='MYR'?'selected':''}>MYR</option><option ${x.currency==='USD'?'selected':''}>USD</option></select></div><div class="field full"><label>Spending Type</label><select name="category" required>${catsOptions(x.category||'')}</select></div>${window.MGWUnifiedWallet?.choiceFields({...x,paymentSelection:x.paymentSourceId?'manual':'unlinked'})||''}<div class="field full"><label>Notes</label><textarea name="notes">${esc(x.notes||'')}</textarea></div><div class="field full"><button class="primary-btn">Save Changes</button></div></form>`}
function openEditor(id){const x=findExpense(id);if(!x)return;const m=document.querySelector('#modal'),body=document.querySelector('#modalBody'),title=document.querySelector('#modalTitle');if(!m||!body||!title)return;title.textContent='Edit Transaction';body.innerHTML=editorForm(x);m.showModal();body.querySelector('#mgwEditExpenseForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget)),amount=Number(o.amount);if(!Number.isFinite(amount)||amount<0)return toast?.('Enter a valid amount');const next=JSON.parse(JSON.stringify(db)),edited=next.expenses.find(row=>row.id===x.id);if(!edited)return;window.MGWUnifiedWallet?.choose(edited,e.currentTarget.querySelector('[data-k="paymentSourceId"]')?.value||'',next);if(amount!==Number(x.amount)||o.currency!==x.currency||o.date!==x.date){delete edited.sgdAmount;delete edited.fxRateToSGD;delete edited.fxRateDate;delete edited.fxRateSource;}Object.assign(edited,{date:o.date,time:o.time||'',vendor:o.vendor||'',location:o.location||'',amount,currency:o.currency||'SGD',category:o.category||'Other',notes:o.notes||'',updatedAt:new Date().toISOString()});try{localStorage.setItem(MGW.key,JSON.stringify(next));window.MGWAdoptDatabase(next)}catch(err){toast?.('Could not save transaction: '+err.message);return}historyDirty=true;m.close();renderAll?.();renderRecent();if(document.querySelector('#view-insights')?.classList.contains('active'))renderHistory(true);toast?.('Transaction updated')}}
function removeExpense(id){const x=findExpense(id);if(!x)return;const label=x.vendor||x.merchant||x.category||'this transaction';if(!confirm(`Delete ${label} for ${money(x.amount)}?\n\nExport a backup first if you may need it later.`))return;const next=JSON.parse(JSON.stringify(db));next.expenses=next.expenses.filter(e=>String(e.id)!==String(id));if(Array.isArray(next.importHistory))next.importHistory=next.importHistory.filter(h=>String(h.acceptedExpenseId||'')!==String(id));try{localStorage.setItem(MGW.key,JSON.stringify(next));window.MGWAdoptDatabase(next)}catch(err){toast?.('Could not delete transaction: '+err.message);return}historyDirty=true;renderAll?.();renderRecent();if(document.querySelector('#view-insights')?.classList.contains('active'))renderHistory(true);toast?.('Transaction deleted')}
function closeSwipes(except=null){document.querySelectorAll('#recentTransactions .mgw-swipe-row.is-open').forEach(row=>{if(row!==except)row.classList.remove('is-open')})}
let swipe=null;
function onPointerDown(e){const row=e.target.closest('#recentTransactions .mgw-swipe-row');if(!row||e.target.closest('button'))return;swipe={row,x:e.clientX,y:e.clientY,dx:0,dy:0}}
function onPointerMove(e){if(!swipe)return;swipe.dx=e.clientX-swipe.x;swipe.dy=e.clientY-swipe.y;if(Math.abs(swipe.dy)>Math.abs(swipe.dx)+8){swipe=null;return}if(Math.abs(swipe.dx)>12)e.preventDefault()}
function onPointerUp(){if(!swipe)return;const {row,dx,dy}=swipe;swipe=null;if(Math.abs(dx)<36||Math.abs(dx)<Math.abs(dy))return;if(dx<0){closeSwipes(row);row.classList.add('is-open')}else row.classList.remove('is-open')}
function onClick(e){const edit=e.target.closest('[data-edit-expense]'),del=e.target.closest('[data-delete-expense]');if(edit){e.preventDefault();e.stopPropagation();openEditor(edit.dataset.editExpense)}else if(del){e.preventDefault();e.stopPropagation();removeExpense(del.dataset.deleteExpense)}else if(e.target.closest('[data-nav="insights"]'))requestAnimationFrame(()=>renderHistory(true));else if(!e.target.closest('#recentTransactions .mgw-swipe-row'))closeSwipes()}
function renderOwned(){if(painting)return;painting=true;try{styles();renderRecent();ensureHistoryCard();historyDirty=true;if(document.querySelector('#view-insights')?.classList.contains('active'))renderHistory()}finally{painting=false}}
function boot(){styles();renderRecent();ensureHistoryCard();document.addEventListener('click',onClick);document.addEventListener('pointerdown',onPointerDown,{passive:true});document.addEventListener('pointermove',onPointerMove,{passive:false});document.addEventListener('pointerup',onPointerUp,{passive:true});document.addEventListener('pointercancel',()=>{swipe=null},{passive:true});if(typeof renderAll==='function'&&!renderAll.__mgwTxEditor){const base=renderAll;renderAll=function(){base();historyDirty=true;queueMicrotask(()=>{renderRecent();if(document.querySelector('#view-insights')?.classList.contains('active'))renderHistory()})};renderAll.__mgwTxEditor=true}document.addEventListener('mgw:data-ready',()=>{historyDirty=true;renderRecent()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.MGWTransactionEditor={version:RELEASE,edit:openEditor,remove:removeExpense,refresh:renderOwned,renderHistory:()=>renderHistory(true)};
})();
