// MoneyGoWhere DEV — edit/delete historical expense transactions
// Local-first only: edits the browser database; no personal transaction data is bundled in source.
(()=>{'use strict';
const RELEASE='1.5.5-dev.26';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v)||0;
const norm=v=>String(v||'').replace(/^[^A-Za-z0-9]+/,'').trim().replace(/\s+/g,' ').toUpperCase();
const persist=()=>localStorage.setItem(MGW.key,JSON.stringify(db));
const merchant=x=>String(x.vendor||x.merchant||x.notes||x.category||'Other').trim()||'Other';
const monthLabel=key=>{const [y,m]=String(key).split('-').map(Number),d=new Date(y,m-1,1);return Number.isNaN(d.getTime())?key:d.toLocaleDateString('en-SG',{month:'long',year:'numeric'})};
function catsOptions(sel=''){return '<option value="">Select category</option>'+Object.keys(MGW.cats).map(c=>`<option value="${esc(c)}" ${c===sel?'selected':''}>${esc(c)}</option>`).join('')}
function styles(){if(document.querySelector('#mgwTxEditorCss'))return;const s=document.createElement('style');s.id='mgwTxEditorCss';s.textContent=`
.mgw-tx-actions{display:flex;gap:6px;justify-content:flex-end;margin-top:6px}.mgw-tx-actions button{border:0;border-radius:9px;padding:6px 9px;font-size:.76rem;font-weight:800;cursor:pointer}.mgw-tx-edit{background:var(--brand-soft,#e8f5f2);color:var(--brand,#0f766e)}.mgw-tx-delete{background:#fff1f2;color:#be123c}.mgw-history-line .mgw-tx-actions{grid-column:1/-1}.tx[data-expense-id]{grid-template-columns:auto minmax(0,1fr) auto}.tx[data-expense-id] .mgw-tx-actions{grid-column:2/-1;margin-top:2px;justify-content:flex-start}@media(max-width:520px){.mgw-tx-actions button{padding:7px 10px}}
`;document.head.appendChild(s)}
function actionButtons(id){return `<div class="mgw-tx-actions"><button type="button" class="mgw-tx-edit" data-edit-expense="${esc(id)}">Edit</button><button type="button" class="mgw-tx-delete" data-delete-expense="${esc(id)}">Delete</button></div>`}
function renderRecentOwned(){const el=document.querySelector('#recentTransactions');if(!el)return;const rows=[...(db.expenses||[])].sort((a,b)=>String((b.date||'')+(b.time||'')).localeCompare(String((a.date||'')+(a.time||'')))).slice(0,12);if(!rows.length){el.className='transaction-list empty-state';el.textContent='Nothing recorded yet.';return}el.className='transaction-list';el.innerHTML=rows.map(x=>`<div class="tx" data-expense-id="${esc(x.id||'')}"><span class="cat-icon">${MGW.cats[x.category]||'📦'}</span><div><b>${esc(x.vendor||x.category||'Expense')}</b><small>${esc(String(x.date||''))}${x.location?' · '+esc(x.location):''}</small>${actionButtons(x.id||'')}</div><span class="amount">${money(x.amount)}</span></div>`).join('')}
function historyLine(x){const meta=[String(x.date||'').slice(0,10),x.time,x.location,x.notes].filter(Boolean).join(' · ');return `<div class="mgw-history-line" data-expense-id="${esc(x.id||'')}"><div><b>${esc(merchant(x))}</b><small>${esc(meta)}</small></div><strong>${money(num(x.amount))}</strong>${actionButtons(x.id||'')}</div>`}
function groupedRows(rows){const map=new Map();for(const x of rows){const name=merchant(x),k=norm(name);if(!map.has(k))map.set(k,{name,rows:[]});map.get(k).rows.push(x)}return [...map.values()].sort((a,b)=>Math.max(...b.rows.map(x=>String(x.date||'').replace(/\D/g,'')||0))-Math.max(...a.rows.map(x=>String(x.date||'').replace(/\D/g,'')||0))).map(g=>{g.rows.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(b.time||'').localeCompare(String(a.time||''))||num(b.amount)-num(a.amount));if(g.rows.length===1)return historyLine(g.rows[0]);const total=g.rows.reduce((t,x)=>t+num(x.amount),0);return `<details class="mgw-history-merchant"><summary><div class="mgw-history-copy"><b>${esc(g.name)}</b><small>${g.rows.length} purchases</small></div><div class="mgw-history-right"><strong>${money(total)}</strong><i class="mgw-ui-chevron">›</i></div></summary><div class="mgw-history-merchant-body">${g.rows.map(historyLine).join('')}</div></details>`}).join('')}
function renderHistoryOwned(){const view=document.querySelector('#view-insights');if(!view)return;let card=document.querySelector('#mgwPurchaseHistory');if(!card){card=document.createElement('article');card.className='card';card.id='mgwPurchaseHistory';view.appendChild(card)}const rows=[...(db.expenses||[])].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(b.time||'').localeCompare(String(a.time||'')));const months=new Map();for(const x of rows){const k=String(x.date||'').slice(0,7)||'Unknown';if(!months.has(k))months.set(k,[]);months.get(k).push(x)}const body=[...months.entries()].sort((a,b)=>b[0].localeCompare(a[0])).map(([k,list])=>{const total=list.reduce((t,x)=>t+num(x.amount),0);return `<details class="mgw-history-month"><summary><div class="mgw-history-copy"><b>${esc(monthLabel(k))}</b><small>${list.length} ${list.length===1?'purchase':'purchases'}</small></div><div class="mgw-history-right"><strong>${money(total)}</strong><i class="mgw-ui-chevron">›</i></div></summary><div class="mgw-history-month-body">${groupedRows(list)}</div></details>`}).join('');card.innerHTML=`<div class="card-head"><div><span class="section-icon">🧾</span><b>Purchase History</b></div></div><p class="mgw-muted">Browse historical purchases by month. Use Edit to correct a record or Delete to remove test/incorrect transactions.</p><div class="mgw-history-list">${body||'<p class="empty-state">No purchase history yet.</p>'}</div>`}
function findExpense(id){return (db.expenses||[]).find(x=>String(x.id)===String(id))}
function editorForm(x){return `<form id="mgwEditExpenseForm" class="form-grid"><div class="field"><label>Date</label><input name="date" type="date" required value="${esc(String(x.date||'').slice(0,10))}"></div><div class="field"><label>Time</label><input name="time" type="time" value="${esc(x.time||'')}"></div><div class="field"><label>Vendor</label><input name="vendor" value="${esc(x.vendor||x.merchant||'')}"></div><div class="field"><label>Location</label><input name="location" value="${esc(x.location||'')}"></div><div class="field"><label>Amount</label><input name="amount" type="number" min="0" step="0.01" required value="${esc(x.amount)}"></div><div class="field"><label>Currency</label><select name="currency"><option ${String(x.currency||'SGD')==='SGD'?'selected':''}>SGD</option><option ${x.currency==='MYR'?'selected':''}>MYR</option><option ${x.currency==='USD'?'selected':''}>USD</option></select></div><div class="field full"><label>Spending Type</label><select name="category" required>${catsOptions(x.category||'')}</select></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(x.notes||'')}</textarea></div><div class="field full"><button class="primary-btn">Save Changes</button></div></form>`}
function openEditor(id){const x=findExpense(id);if(!x)return;const m=document.querySelector('#modal'),body=document.querySelector('#modalBody'),title=document.querySelector('#modalTitle');if(!m||!body||!title)return;title.textContent='Edit Transaction';body.innerHTML=editorForm(x);m.showModal();const f=body.querySelector('#mgwEditExpenseForm');f.onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(f));const amount=Number(o.amount);if(!Number.isFinite(amount)||amount<0){if(typeof toast==='function')toast('Enter a valid amount');return}Object.assign(x,{date:o.date,time:o.time||'',vendor:o.vendor||'',location:o.location||'',amount,currency:o.currency||'SGD',category:o.category||'Other',notes:o.notes||'',updatedAt:new Date().toISOString()});persist();m.close();if(typeof renderAll==='function')renderAll();renderOwned();if(typeof toast==='function')toast('Transaction updated')}}
function removeExpense(id){const x=findExpense(id);if(!x)return;const label=x.vendor||x.merchant||x.category||'this transaction';if(!confirm(`Delete ${label} for ${money(x.amount)}?\n\nThis removes it from your local MoneyGoWhere data. Export a backup first if you may need it later.`))return;db.expenses=db.expenses.filter(e=>String(e.id)!==String(id));if(Array.isArray(db.importHistory)){db.importHistory=db.importHistory.filter(h=>String(h.acceptedExpenseId||'')!==String(id)&&!(x.sourceId&&h.status==='accepted'&&String(h.sourceId||'')===String(x.sourceId)))}persist();if(typeof renderAll==='function')renderAll();renderOwned();if(typeof toast==='function')toast('Transaction deleted')}
function bindActions(root=document){root.querySelectorAll('[data-edit-expense]').forEach(b=>{if(b.dataset.mgwBound)return;b.dataset.mgwBound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openEditor(b.dataset.editExpense)})});root.querySelectorAll('[data-delete-expense]').forEach(b=>{if(b.dataset.mgwBound)return;b.dataset.mgwBound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();removeExpense(b.dataset.deleteExpense)})})}
let painting=false;function renderOwned(){if(painting)return;painting=true;try{styles();renderRecentOwned();renderHistoryOwned();bindActions()}finally{painting=false}}
function boot(){renderOwned();if(typeof renderAll==='function'&&!renderAll.__mgwTxEditor){const base=renderAll;renderAll=function(){base();queueMicrotask(renderOwned)};renderAll.__mgwTxEditor=true}const observer=new MutationObserver(()=>queueMicrotask(()=>{if(!painting)bindActions()}));observer.observe(document.body,{subtree:true,childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.MGWTransactionEditor={version:RELEASE,edit:openEditor,remove:removeExpense,refresh:renderOwned};})();